# Generated by Django 5.1.13 on 2025-10-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siaes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsiae",
            name="name",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Raison sociale"),
        ),
        migrations.AlterField(
            model_name="siae",
            name="name",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Raison sociale"),
        ),
    ]
