# Generated by Django 5.1.13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siaes", "0003_siae_decp_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsiae",
            name="decp_last_sync_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Date de dernière synchronisation (DECP)",
            ),
        ),
        migrations.AddField(
            model_name="historicalsiae",
            name="has_won_contract_last_3_years",
            field=models.BooleanField(
                default=False,
                verbose_name="A remporté un marché public ces 3 dernières années (DECP)",
            ),
        ),
    ]
