# Generated by Django 3.2.4 on 2021-09-02 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('siaes', '0003_siae_add_missing_fields_update_others'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiaeNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('brand', models.CharField(blank=True, max_length=255, verbose_name='Enseigne')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Réseau',
                'verbose_name_plural': 'Réseaux',
            },
        ),
    ]
