# Generated by Django 5.2 on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siaes", "0004_siae_public_market"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsiae",
            name="decp_last_sync_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Date de dernière synchronisation (DECP)",
            ),
        ),
        migrations.AddField(
            model_name="historicalsiae",
            name="has_won_contract_last_3_years",
            field=models.BooleanField(
                default=False,
                verbose_name="A remporté un marché public ces 3 dernières années (DECP)",
            ),
        ),
        migrations.AlterField(
            model_name="siaepublicmarket",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
