# Generated by Django 3.2.4 on 2021-09-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siaes', '0004_siaenetwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='siae',
            name='networks',
            field=models.ManyToManyField(blank=True, related_name='siaes', to='siaes.SiaeNetwork', verbose_name='Réseaux'),
        ),
    ]
