# Generated by Django 3.2.7 on 2021-09-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0005_alter_siae_sectors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="siae",
            old_name="createdat",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="siae",
            old_name="updatedat",
            new_name="updated_at",
        ),
    ]
