# Generated by Django 3.2.4 on 2021-09-03 12:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siaes', '0006_siae_networks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siae',
            old_name='createdat',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='siae',
            old_name='updatedat',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='siae',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siae',
            name='admin_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siae',
            name='c1_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siae',
            name='c1_source',
            field=models.CharField(blank=True, choices=[('ASP', 'Export ASP'), ('GEIQ', 'Export GEIQ'), ('EA_EATT', 'Export EA+EATT'), ('USER_CREATED', 'Utilisateur (Antenne)'), ('STAFF_CREATED', 'Staff Itou')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='siae',
            name='c4_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siae',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='siae',
            name='ig_ca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siae',
            name='ig_date_constitution',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siae',
            name='ig_employees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siae',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='siae',
            name='is_cocontracting',
            field=models.BooleanField(default=False, verbose_name='Co-traitance'),
        ),
        migrations.AddField(
            model_name='siae',
            name='is_consortium',
            field=models.BooleanField(default=False, verbose_name='Consortium'),
        ),
        migrations.AddField(
            model_name='siae',
            name='is_delisted',
            field=models.BooleanField(default=False, verbose_name='Masquée'),
        ),
        migrations.AddField(
            model_name='siae',
            name='is_first_page',
            field=models.BooleanField(default=False, verbose_name='A la une'),
        ),
        migrations.AddField(
            model_name='siae',
            name='last_sync_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siae',
            name='nature',
            field=models.CharField(blank=True, choices=[('HEAD_OFFICE', 'Conventionné avec la Direccte'), ('ANTENNA', 'Rattaché à un autre conventionnement')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='siae',
            name='presta_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('DISP', 'Mise à disposition - Interim'), ('PREST', 'Prestation de service'), ('BUILD', 'Fabrication et commercialisation de biens')], max_length=20), blank=True, null=True, size=None, verbose_name='Codes postaux'),
        ),
        migrations.AddField(
            model_name='siae',
            name='qpv_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='siae',
            name='qpv_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siae',
            name='siret_is_valid',
            field=models.BooleanField(default=False, verbose_name='Siret Valide'),
        ),
        migrations.AddField(
            model_name='siae',
            name='sync_skip',
            field=models.BooleanField(default=False),
        ),
    ]
