# Generated by Django 3.2.4 on 2021-09-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siaes', '0007_siae_add_missing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siae',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
    ]
