# Generated by Django 3.2.4 on 2021-09-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0002_sector'),
        ('siaes', '0008_alter_siae_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siae',
            name='sectors',
            field=models.ManyToManyField(to='sectors.Sector'),
        ),
    ]
