# Generated by Django 3.2.4 on 2021-09-06 11:43

from django.db import migrations, models
import lemarche.siaes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('siaes', '0009_alter_siae_sectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siae',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Enseigne'),
        ),
        migrations.AlterField(
            model_name='siae',
            name='naf',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[lemarche.siaes.validators.validate_naf], verbose_name='Naf'),
        ),
        migrations.AlterField(
            model_name='siae',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
    ]
