# Generated by Django 3.2.7 on 2021-09-15 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("siaes", "0009_siaeclientreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="siaes", to=settings.AUTH_USER_MODEL, verbose_name="Gestionnaires"
            ),
        ),
    ]
