# Generated by Django 3.2.7 on 2021-09-24 13:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0010_siae_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="kind",
            field=models.CharField(
                choices=[
                    ("EI", "Entreprise d'insertion"),
                    ("AI", "Association intermédiaire"),
                    ("ACI", "Atelier chantier d'insertion"),
                    ("ETTI", "Entreprise de travail temporaire d'insertion"),
                    ("EITI", "Entreprise d'insertion par le travail indépendant"),
                    ("GEIQ", "Groupement d'employeurs pour l'insertion et la qualification"),
                    ("EA", "Entreprise adaptée"),
                    ("EATT", "Entreprise adaptée de travail temporaire"),
                ],
                default="EI",
                max_length=6,
                verbose_name="Type de structure",
            ),
        ),
        migrations.AlterField(
            model_name="siae",
            name="presta_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DISP", "Mise à disposition - Interim"),
                        ("PREST", "Prestation de service"),
                        ("BUILD", "Fabrication et commercialisation de biens"),
                    ],
                    max_length=20,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Type de prestation",
            ),
        ),
    ]
