# Generated by Django 3.2.7 on 2021-09-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0011_auto_20210924_1528"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="nature",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HEAD_OFFICE", "Conventionné avec la Direccte"),
                    ("ANTENNA", "Rattaché à un autre conventionnement"),
                ],
                max_length=20,
                null=True,
                verbose_name="Établissement",
            ),
        ),
    ]
