# Generated by Django 3.2.7 on 2021-09-29 14:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0014_update_siae_perimeter_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siae",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="siae",
            name="longitude",
        ),
        migrations.AddField(
            model_name="siae",
            name="coords",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
