# Generated by Django 3.2.7 on 2021-10-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0015_siae_replace_latlng_with_coords"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="E-mail"),
        ),
        migrations.AddField(
            model_name="siae",
            name="contact_first_name",
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Prénom"),
        ),
        migrations.AddField(
            model_name="siae",
            name="contact_last_name",
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Nom"),
        ),
        migrations.AddField(
            model_name="siae",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Téléphone"),
        ),
        migrations.AddField(
            model_name="siae",
            name="contact_website",
            field=models.URLField(blank=True, null=True, verbose_name="Site internet"),
        ),
    ]
