# Generated by Django 3.2.7 on 2021-10-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0015_siae_replace_latlng_with_coords"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="slug",
            field=models.SlugField(max_length=255, null=True, verbose_name="Slug"),
        ),
    ]
