# Generated by Django 3.2.7 on 2021-10-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0017_siae_slug_populate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
        ),
    ]
