# Generated by Django 3.2.8 on 2021-10-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0018_alter_siae_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="logo_url",
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="Lien vers le logo"),
        ),
        migrations.AlterField(
            model_name="siae",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="Site internet"),
        ),
    ]
