# Generated by Django 3.2.8 on 2021-10-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0018_alter_siae_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="siae",
            old_name="c4_id",
            new_name="c4_id_old",
        ),
        migrations.AlterField(
            model_name="siae",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="Site internet"),
        ),
    ]
