# Generated by Django 3.2.8 on 2021-10-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0020_siae_siaeclientreference_logo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="image_name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de l'image"),
        ),
    ]
