# Generated by Django 3.2.8 on 2021-10-20 22:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("siaes", "0021_siae_image_name"),
    ]

    state_operations = [
        migrations.CreateModel(
            name="SiaeUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date de modification")),
                ("siae", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="siaes.siae")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelTable(
            name="siaeuser",
            table="siaes_siae_users",
        ),
        migrations.AlterField(
            model_name="siae",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="siaes",
                through="siaes.SiaeUser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Gestionnaires",
            ),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.AddField(
            model_name="SiaeUser",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
        ),
        migrations.AddField(
            model_name="SiaeUser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Date de modification"),
        ),
    ]
