# Generated by Django 3.2.8 on 2021-10-21 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0022_siae_users_m2m_add_through"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siaeuser",
            options={"verbose_name": "Gestionnaire", "verbose_name_plural": "Gestionnaires"},
        ),
        migrations.AddField(
            model_name="siaeuser",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
        ),
        migrations.AddField(
            model_name="siaeuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Date de modification"),
        ),
    ]
