# Generated by Django 3.2.8 on 2021-10-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0023_siae_users_through_add_timestamps"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siaeuser",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Gestionnaire",
                "verbose_name_plural": "Gestionnaires",
            },
        ),
        migrations.AlterField(
            model_name="siae",
            name="contact_website",
            field=models.URLField(
                blank=True, help_text="Doit commencer par http:// ou https://", null=True, verbose_name="Site internet"
            ),
        ),
    ]
