# Generated by Django 3.2.8 on 2021-11-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0026_rename_c1_source_siae_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="kind",
            field=models.CharField(
                choices=[
                    ("EI", "Entreprise d'insertion (EI)"),
                    ("AI", "Association intermédiaire (AI)"),
                    ("ACI", "Atelier chantier d'insertion (ACI)"),
                    ("ETTI", "Entreprise de travail temporaire d'insertion (ETTI)"),
                    ("EITI", "Entreprise d'insertion par le travail indépendant (EITI)"),
                    ("GEIQ", "Groupement d'employeurs pour l'insertion et la qualification (GEIQ)"),
                    ("EA", "Entreprise adaptée (EA)"),
                    ("EATT", "Entreprise adaptée de travail temporaire (EATT)"),
                    ("ESAT", "Etablissement et service d'aide par le travail (ESAT)"),
                ],
                default="EI",
                max_length=6,
                verbose_name="Type de structure",
            ),
        ),
        migrations.AlterField(
            model_name="siae",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ASP", "Export ASP"),
                    ("GEIQ", "Export GEIQ"),
                    ("EA_EATT", "Export EA+EATT"),
                    ("USER_CREATED", "Utilisateur (Antenne)"),
                    ("STAFF_CREATED", "Staff Itou"),
                    ("ESAT", "Import ESAT (GSAT, Handeco)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
