# Generated by Django 3.2.8 on 2021-11-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0027_alter_siae_kind_source_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="import_raw_object",
            field=models.JSONField(editable=False, null=True, verbose_name="Donnée JSON brute"),
        ),
    ]
