# Generated by Django 3.2.8 on 2021-11-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0028_siae_import_raw_object"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="client_reference_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="siae",
            name="label_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="siae",
            name="network_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="siae",
            name="offer_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="siae",
            name="sector_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="siae",
            name="user_count",
            field=models.IntegerField(default=0),
        ),
    ]
