# Generated by Django 3.2.8 on 2021-11-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0029_siae_count_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="nature",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HEAD_OFFICE", "Conventionné par la DREETS"),
                    ("ANTENNA", "Rattaché à un autre conventionnement"),
                ],
                max_length=20,
                null=True,
                verbose_name="Établissement",
            ),
        ),
    ]
