# Generated by Django 3.2.8 on 2021-11-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0030_alter_siae_nature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="ig_ca",
            field=models.IntegerField(blank=True, null=True, verbose_name="Chiffre d'affaire (API Entreprise)"),
        ),
        migrations.AlterField(
            model_name="siae",
            name="ig_date_constitution",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de création (API Entreprise)"),
        ),
        migrations.AlterField(
            model_name="siae",
            name="ig_employees",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nombre de salariés (API Entreprise)"
            ),
        ),
        migrations.AlterField(
            model_name="siae",
            name="qpv_code",
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name="Code de la zone QPV"),
        ),
        migrations.AlterField(
            model_name="siae",
            name="qpv_name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de la zone QPV"),
        ),
    ]
