# Generated by Django 3.2.8 on 2021-11-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0032_avoid_null_on_charfields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-mail"),
        ),
    ]
