# Generated by Django 3.2.8 on 2021-11-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0032_avoid_null_on_charfields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="siae",
            old_name="ig_ca",
            new_name="api_entreprise_ca",
        ),
        migrations.RenameField(
            model_name="siae",
            old_name="ig_date_constitution",
            new_name="api_entreprise_date_constitution",
        ),
        migrations.RenameField(
            model_name="siae",
            old_name="ig_employees",
            new_name="api_entreprise_employees",
        ),
        migrations.AddField(
            model_name="siae",
            name="api_entreprise_etablissement_last_sync_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de dernière synchronisation (API Entreprise /etablissements)"
            ),
        ),
        migrations.AddField(
            model_name="siae",
            name="api_entreprise_ca_date_fin_exercice",
            field=models.DateField(blank=True, null=True, verbose_name="Date de fin de l'exercice (API Entreprise)"),
        ),
        migrations.AddField(
            model_name="siae",
            name="api_entreprise_employees_year_reference",
            field=models.CharField(
                blank=True, max_length=4, verbose_name="Année de référence du nombre de salariés (API Entreprise)"
            ),
        ),
        migrations.AddField(
            model_name="siae",
            name="api_entreprise_exercice_last_sync_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de dernière synchronisation (API Entreprise /exercices)"
            ),
        ),
    ]
