# Generated by Django 3.2.8 on 2021-11-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0035_siae_update_api_entreprise_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="api_entreprise_date_constitution",
            field=models.DateField(blank=True, null=True, verbose_name="Date de création (API Entreprise)"),
        ),
    ]
