# Generated by Django 3.2.8 on 2021-11-14 22:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0036_alter_siae_api_entreprise_date_constitution"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiaeImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("image_name", models.CharField(max_length=255, verbose_name="Nom de l'image")),
                (
                    "image_url",
                    models.URLField(blank=True, max_length=500, null=True, verbose_name="Lien vers l'image"),
                ),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Ordre")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date de modification")),
                (
                    "siae",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="siaes.siae",
                        verbose_name="Structure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
    ]
