# Generated by Django 3.2.8 on 2021-11-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0037_siaeimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="image_count",
            field=models.IntegerField(default=0, verbose_name="Nombre d'images"),
        ),
    ]
