# Generated by Django 3.2.8 on 2021-12-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0038_siae_image_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="api_qpv_last_sync_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de dernière synchronisation (API QPV)"
            ),
        ),
    ]
