# Generated by Django 4.0 on 2021-12-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0038_siae_image_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="api_qpv_last_sync_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de dernière synchronisation (API QPV)"
            ),
        ),
        migrations.AlterField(
            model_name="siae",
            name="is_qpv",
            field=models.BooleanField(default=False, verbose_name="Zone QPV (API QPV)"),
        ),
        migrations.AlterField(
            model_name="siae",
            name="qpv_code",
            field=models.CharField(blank=True, max_length=16, verbose_name="Code de la zone QPV (API QPV)"),
        ),
        migrations.AlterField(
            model_name="siae",
            name="qpv_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Nom de la zone QPV (API QPV)"),
        ),
    ]
