# Generated by Django 4.0.1 on 2022-01-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siaes', '0039_siae_api_qpv_last_sync_date_alter_siae_is_qpv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siae',
            name='api_zrr_last_sync_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de dernière synchronisation (API ZRR)'),
        ),
        migrations.AddField(
            model_name='siae',
            name='is_zrr',
            field=models.BooleanField(default=False, verbose_name='Zone ZRR (API ZRR)'),
        ),
        migrations.AddField(
            model_name='siae',
            name='zrr_code',
            field=models.CharField(blank=True, max_length=16, verbose_name='Code de la zone ZRR (API ZRR)'),
        ),
        migrations.AddField(
            model_name='siae',
            name='zrr_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom de la zone ZRR (API ZRR)'),
        ),
    ]
