# Generated by Django 4.0.2 on 2022-02-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0041_alter_siae_kind_alter_siae_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="asp_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="ID ASP"),
        ),
    ]
