# Generated by Django 4.0.2 on 2022-02-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0042_siae_asp_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="c2_etp_count",
            field=models.FloatField(blank=True, null=True, verbose_name="Nombre d'ETP (C2)"),
        ),
        migrations.AddField(
            model_name="siae",
            name="c2_etp_count_date_saisie",
            field=models.DateField(blank=True, null=True, verbose_name="Date de saisie du nombre d'ETP (C2)"),
        ),
        migrations.AddField(
            model_name="siae",
            name="c2_etp_count_last_sync_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de dernière synchronisation (C2 ETP)"
            ),
        ),
    ]
