# Generated by Django 4.0.2 on 2022-02-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0044_siae_content_filled_basic_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="signup_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date d'inscription de la structure (premier utilisateur)"
            ),
        ),
    ]
