# Generated by Django 4.0.2 on 2022-03-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0047_alter_siae_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="ca",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Chiffre d'affaire"),
        ),
        migrations.AddField(
            model_name="siae",
            name="ca_last_updated",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de dernière mise à jour du chiffre d'affaire"
            ),
        ),
        migrations.AddField(
            model_name="siae",
            name="employees_insertion_count",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre de salariés en insertion"),
        ),
        migrations.AddField(
            model_name="siae",
            name="employees_insertion_count_last_updated",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de dernière mise à jour du nombre de salariés en insertion"
            ),
        ),
        migrations.AddField(
            model_name="siae",
            name="employees_permanent_count",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre de salariés permanents"),
        ),
        migrations.AddField(
            model_name="siae",
            name="employees_permanent_count_last_updated",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de dernière mise à jour du nombre de salariés permanents"
            ),
        ),
        migrations.AddField(
            model_name="siae",
            name="year_constitution",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Année de création"),
        ),
    ]
