# Generated by Django 4.0.2 on 2022-03-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0047_alter_siae_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="source",
            field=models.CharField(
                choices=[
                    ("ASP", "Export ASP"),
                    ("GEIQ", "Export GEIQ"),
                    ("EA_EATT", "Export EA+EATT"),
                    ("USER_CREATED", "Utilisateur (Antenne)"),
                    ("STAFF_C1_CREATED", "Staff C1"),
                    ("STAFF_C4_CREATED", "Staff C4"),
                    ("ESAT", "Import ESAT (GSAT, Handeco)"),
                    ("SEP", "Import SEP"),
                ],
                default="STAFF_C4_CREATED",
                max_length=20,
            ),
        ),
    ]
