# Generated by Django 4.0.2 on 2022-03-14 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0048_siae_ca_siae_ca_last_updated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiaeGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                ("siret", models.CharField(blank=True, max_length=14, verbose_name="Siret")),
                ("contact_first_name", models.CharField(blank=True, max_length=150, verbose_name="Prénom")),
                ("contact_last_name", models.CharField(blank=True, max_length=150, verbose_name="Nom")),
                (
                    "contact_website",
                    models.URLField(
                        blank=True, help_text="Doit commencer par http:// ou https://", verbose_name="Site internet"
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254, verbose_name="E-mail")),
                ("contact_phone", models.CharField(blank=True, max_length=150, verbose_name="Téléphone")),
                ("logo_url", models.URLField(blank=True, max_length=500, verbose_name="Lien vers le logo")),
                (
                    "year_constitution",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Année de création"),
                ),
                (
                    "siae_count",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre de structures"),
                ),
                (
                    "siae_count_last_updated",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de dernière mise à jour du nombre de structures"
                    ),
                ),
                (
                    "employees_insertion_count",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre de salariés en insertion"),
                ),
                (
                    "employees_insertion_count_last_updated",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Date de dernière mise à jour du nombre de salariés en insertion",
                    ),
                ),
                (
                    "employees_permanent_count",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre de salariés permanents"),
                ),
                (
                    "employees_permanent_count_last_updated",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Date de dernière mise à jour du nombre de salariés permanents",
                    ),
                ),
                ("ca", models.PositiveIntegerField(blank=True, null=True, verbose_name="Chiffre d'affaire")),
                (
                    "ca_last_updated",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de dernière mise à jour du chiffre d'affaire"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date de modification")),
            ],
            options={
                "verbose_name": "Groupement",
                "verbose_name_plural": "Groupements",
            },
        ),
    ]
