# Generated by Django 4.0.2 on 2022-03-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0051_siaegroup_sectors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siae",
            options={"ordering": ["name"], "verbose_name": "Structure", "verbose_name_plural": "Structures"},
        ),
    ]
