# Generated by Django 4.0.2 on 2022-03-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0052_alter_siae_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="contact_social_website",
            field=models.URLField(
                blank=True, help_text="Doit commencer par http:// ou https://", verbose_name="Réseau social"
            ),
        ),
        migrations.AddField(
            model_name="siaegroup",
            name="contact_social_website",
            field=models.URLField(
                blank=True, help_text="Doit commencer par http:// ou https://", verbose_name="Réseau social"
            ),
        ),
    ]
