# Generated by Django 4.0.4 on 2022-04-13 08:10

from django.db import migrations, models

import lemarche.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0053_siae_contact_social_website_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="presta_type",
            field=lemarche.utils.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DISP", "Mise à disposition - Interim"),
                        ("PREST", "Prestation de service"),
                        ("BUILD", "Fabrication et commercialisation de biens"),
                    ],
                    max_length=20,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Type de prestation",
            ),
        ),
    ]
