# Generated by Django 4.1.6 on 2023-02-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0055_alter_siae_is_active_alter_siae_is_delisted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Le contact renseigné ici recevra les opportunités commerciales par mail",
                max_length=254,
                verbose_name="E-mail",
            ),
        ),
    ]
