# Generated by Django 4.1.7 on 2023-05-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0057_siae_logs"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SiaeLabel",
            new_name="SiaeLabelOld",
        ),
        migrations.RunSQL("ALTER sequence siaes_siaelabel_id_seq RENAME TO siaes_siaelabelold_id_seq;"),
    ]
