# Generated by Django 4.1.7 on 2023-05-30 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0058_siaelabel_old"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siaelabelold",
            options={
                "verbose_name": "Label & certification (old)",
                "verbose_name_plural": "Labels & certifications (old)",
            },
        ),
        migrations.RenameField(
            model_name="siaelabelold",
            old_name="siae",
            new_name="siae_old",
        ),
        migrations.AlterField(
            model_name="siaelabelold",
            name="siae_old",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels_old",
                to="siaes.siae",
                verbose_name="Structure",
            ),
        ),
    ]
