# Generated by Django 4.1.7 on 2023-05-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
        ("siaes", "0059_siaelabel_through_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                related_name="siaes",
                through="siaes.SiaeLabel",
                to="labels.label",
                verbose_name="Labels & certifications",
            ),
        ),
    ]
