# Generated by Django 4.1.7 on 2023-06-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0060_siae_labels_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="group_count",
            field=models.IntegerField(default=0, verbose_name="Nombre de groupements"),
        ),
    ]
