# Generated by Django 4.1.7 on 2023-06-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0061_alter_siae_geo_range_alter_siae_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="group_count",
            field=models.IntegerField(default=0, verbose_name="Nombre de groupements"),
        ),
    ]
