# Generated by Django 4.2.2 on 2023-06-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0062_siae_group_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="api_entreprise_entreprise_last_sync_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de dernière synchronisation (API Entreprise /entreprises)"
            ),
        ),
        migrations.AddField(
            model_name="siae",
            name="api_entreprise_forme_juridique",
            field=models.CharField(blank=True, max_length=255, verbose_name="Forme juridique (API Entreprise)"),
        ),
        migrations.AddField(
            model_name="siae",
            name="api_entreprise_forme_juridique_code",
            field=models.CharField(
                blank=True, max_length=5, verbose_name="Code de la forme juridique (API Entreprise)"
            ),
        ),
    ]
