# Generated by Django 4.2.2 on 2023-06-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0063_siae_api_entreprise_forme_juridique"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="legal_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ASSOCIATION", "Association"),
                    ("SARL", "SARL"),
                    ("SARL_COOP", "SARL coopérative"),
                    ("SAS", "SAS (Société par actions simplifiée)"),
                    ("SA", "SA (Société anonyme)"),
                    ("SA_COOP", "SA coopérative"),
                    ("SNC", "SNC (Société en nom collectif)"),
                    ("GROUPEMENT_EMPLOYEUR", "Groupement d'employeurs"),
                    ("COLLECTIVITE", "Collectivité"),
                    ("CCAS", "CCAS (Centre (inter)communal d'action sociale)"),
                    ("EPSMS", "EPSMS (Établissement public social ou médico-social)"),
                    ("FONDATION", "Fondation"),
                    ("AUTRE", "Autre"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Forme juridique",
            ),
        ),
    ]
