# Generated by Django 4.2.2 on 2023-06-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0063_siae_api_entreprise_forme_juridique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="api_entreprise_ca",
            field=models.IntegerField(blank=True, null=True, verbose_name="Chiffre d'affaires (API Entreprise)"),
        ),
        migrations.AlterField(
            model_name="siae",
            name="ca",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Chiffre d'affaires"),
        ),
        migrations.AlterField(
            model_name="siae",
            name="ca_last_updated",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de dernière mise à jour du chiffre d'affaires"
            ),
        ),
        migrations.AlterField(
            model_name="siaegroup",
            name="ca",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Chiffre d'affaires"),
        ),
        migrations.AlterField(
            model_name="siaegroup",
            name="ca_last_updated",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de dernière mise à jour du chiffre d'affaires"
            ),
        ),
    ]
