# Generated by Django 4.2.2 on 2023-10-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siaes", "0065_siae_legal_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="etablissement_count",
            field=models.IntegerField(default=0, verbose_name="Nombre d'établissements (à partir du Siren)"),
        ),
    ]
