# Generated by Django 4.2.2 on 2023-09-24 22:27

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siaes", "0066_siae_search_vector"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="siae",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="siaes_siae_search__200779_gin"
            ),
        ),
    ]
