# Generated by Django 4.2.2 on 2023-12-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siaes", "0068_siae_tender_count_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="super_badge",
            field=models.BooleanField(
                blank=True,
                help_text="Champ recalculé à intervalles réguliers",
                null=True,
                verbose_name="Badge 'Super prestataire inclusif'",
            ),
        ),
        migrations.AddField(
            model_name="siae",
            name="super_badge_last_updated",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Date de dernière mise à jour du badge 'Super prestataire inclusif'",
            ),
        ),
    ]
