# Generated by Django 4.2.2 on 2023-09-24 22:18

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siaes", "0071_alter_siae_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True, verbose_name="Search vector"),
        ),
    ]
