# Generated by Django 4.2.9 on 2024-02-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siaes", "0071_alter_siae_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="siae",
            name="extra_data",
            field=models.JSONField(default=dict, editable=False, verbose_name="Données complémentaires"),
        ),
    ]
