# Generated by Django 4.2.13 on 2024-05-17 15:20

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siaes", "0073_siae_brevo_company_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siae",
            name="contact_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=150, region=None, verbose_name="Téléphone"
            ),
        ),
        migrations.AlterField(
            model_name="siaegroup",
            name="contact_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=150, region=None, verbose_name="Téléphone"
            ),
        ),
    ]
