# Generated by Django 4.2.15 on 2024-11-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siaes", "0077_remove_siaeactivity_location_siaeactivity_locations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsiae",
            name="brand",
            field=models.CharField(blank=True, max_length=255, verbose_name="Nom commercial"),
        ),
        migrations.AlterField(
            model_name="siae",
            name="brand",
            field=models.CharField(blank=True, max_length=255, verbose_name="Nom commercial"),
        ),
    ]
