# Generated by Django 4.2.15 on 2024-12-04 16:51

from django.db import migrations, models

import lemarche.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("siaes", "0078_alter_historicalsiae_brand_alter_siae_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsiae",
            name="contact_social_website",
            field=models.URLField(
                blank=True,
                help_text="Doit commencer par http:// ou https://",
                validators=[lemarche.utils.validators.OptionalSchemeURLValidator()],
                verbose_name="Réseau social",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsiae",
            name="contact_website",
            field=models.URLField(
                blank=True,
                help_text="Doit commencer par http:// ou https://",
                validators=[lemarche.utils.validators.OptionalSchemeURLValidator()],
                verbose_name="Site internet",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsiae",
            name="website",
            field=models.URLField(
                blank=True,
                validators=[lemarche.utils.validators.OptionalSchemeURLValidator()],
                verbose_name="Site internet",
            ),
        ),
        migrations.AlterField(
            model_name="siae",
            name="contact_social_website",
            field=models.URLField(
                blank=True,
                help_text="Doit commencer par http:// ou https://",
                validators=[lemarche.utils.validators.OptionalSchemeURLValidator()],
                verbose_name="Réseau social",
            ),
        ),
        migrations.AlterField(
            model_name="siae",
            name="contact_website",
            field=models.URLField(
                blank=True,
                help_text="Doit commencer par http:// ou https://",
                validators=[lemarche.utils.validators.OptionalSchemeURLValidator()],
                verbose_name="Site internet",
            ),
        ),
        migrations.AlterField(
            model_name="siae",
            name="website",
            field=models.URLField(
                blank=True,
                validators=[lemarche.utils.validators.OptionalSchemeURLValidator()],
                verbose_name="Site internet",
            ),
        ),
        migrations.AlterField(
            model_name="siaegroup",
            name="contact_social_website",
            field=models.URLField(
                blank=True,
                help_text="Doit commencer par http:// ou https://",
                validators=[lemarche.utils.validators.OptionalSchemeURLValidator()],
                verbose_name="Réseau social",
            ),
        ),
        migrations.AlterField(
            model_name="siaegroup",
            name="contact_website",
            field=models.URLField(
                blank=True,
                help_text="Doit commencer par http:// ou https://",
                validators=[lemarche.utils.validators.OptionalSchemeURLValidator()],
                verbose_name="Site internet",
            ),
        ),
    ]
