# Generated by Django 4.2.15 on 2025-01-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siaes", "0079_alter_historicalsiae_contact_social_website_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalsiae",
            old_name="is_cocontracting",
            new_name="_is_cocontracting",
        ),
        migrations.RenameField(
            model_name="siae",
            old_name="is_cocontracting",
            new_name="_is_cocontracting",
        ),
        migrations.AlterField(
            model_name="historicalsiae",
            name="_is_cocontracting",
            field=models.BooleanField(default=False, verbose_name="Co-traitance (Fonctionnalité désactivée)"),
        ),
        migrations.AlterField(
            model_name="siae",
            name="_is_cocontracting",
            field=models.BooleanField(default=False, verbose_name="Co-traitance (Fonctionnalité désactivée)"),
        ),
    ]
