# Generated by Django 4.2.15 on 2025-01-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siaes", "0079_alter_historicalsiae_contact_social_website_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsiae",
            name="is_cocontracting",
        ),
        migrations.RemoveField(
            model_name="siae",
            name="is_cocontracting",
        ),
        migrations.AddField(
            model_name="historicalsiae",
            name="_is_cocontracting",
            field=models.BooleanField(default=False, verbose_name="Fonctionnalité désactivée"),
        ),
        migrations.AddField(
            model_name="siae",
            name="_is_cocontracting",
            field=models.BooleanField(default=False, verbose_name="Fonctionnalité désactivée"),
        ),
    ]
