# Generated by Django 4.2.17 on 2025-01-23 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siaes", "0080_remove_historicalsiae_is_cocontracting_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsiae",
            name="geo_range",
        ),
        migrations.RemoveField(
            model_name="historicalsiae",
            name="geo_range_custom_distance",
        ),
        migrations.RemoveField(
            model_name="siae",
            name="geo_range",
        ),
        migrations.RemoveField(
            model_name="siae",
            name="geo_range_custom_distance",
        ),
        migrations.RemoveField(
            model_name="siae",
            name="sectors",
        ),
    ]
