# Generated by Django 4.2.17 on 2025-01-24 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siaes", "0081_remove_historicalsiae_geo_range_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsiae",
            name="presta_type",
        ),
        migrations.RemoveField(
            model_name="siae",
            name="presta_type",
        ),
    ]
