# Generated by Django 4.2.17 on 2025-01-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siaes", "0081_fix_improper_migration"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="siaeuser",
            constraint=models.UniqueConstraint(
                models.F("siae"), models.F("user"), name="unique_siae_user_for_siaeuser"
            ),
        ),
    ]
