# Generated by Django 4.2.17 on 2025-01-23 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siaes", "0082_siaeuser_unique_siae_user_for_siaeuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsiae",
            name="geo_range",
        ),
        migrations.RemoveField(
            model_name="historicalsiae",
            name="geo_range_custom_distance",
        ),
        migrations.RemoveField(
            model_name="siae",
            name="geo_range",
        ),
        migrations.RemoveField(
            model_name="siae",
            name="geo_range_custom_distance",
        ),
        migrations.RemoveField(
            model_name="siae",
            name="sectors",
        ),
    ]
