# Generated by Django 5.1.6 on 2025-03-19 17:08

from django.db import migrations, models

import lemarche.utils.fields


def set_all_presta_types(apps, schema_editor):
    """Presta types are required but because of failed migrations some were empty.
    To handle these case, it has been chosen to select all presta types as an alternative
    for the empty ones"""
    SiaeActivity = apps.get_model("siaes", "SiaeActivity")
    SiaeActivity.objects.filter(presta_type=None).update(presta_type=["DISP", "PREST", "BUILD"])


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0084_remove_historicalsiae_presta_type_and_more"),
    ]

    operations = [
        migrations.RunPython(set_all_presta_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="siaeactivity",
            name="presta_type",
            field=lemarche.utils.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DISP", "Mise à disposition - Interim"),
                        ("PREST", "Prestation de service"),
                        ("BUILD", "Fabrication et commercialisation de biens"),
                    ],
                    max_length=20,
                ),
                db_index=True,
                size=None,
                verbose_name="Type de prestation",
            ),
        ),
    ]
