# Generated by Django 5.1.6 on 2025-03-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0086_alter_siaeactivity_sector_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siaeactivity",
            name="sector_group",
        ),
    ]
