# Generated by Django 5.1.6 on 2025-03-03 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0086_remove_siaeactivity_sector_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="siaeactivity",
            name="sector",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="siae_activity",
                to="sectors.sector",
                verbose_name="Activité",
            ),
            preserve_default=False,
        ),
    ]
