# Generated by Django 5.1.6 on 2025-07-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0089_delete_sectors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsiae",
            name="contact_social_website",
            field=models.URLField(
                blank=True, help_text="Doit commencer par http:// ou https://", verbose_name="Réseau social"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsiae",
            name="contact_website",
            field=models.URLField(
                blank=True, help_text="Doit commencer par http:// ou https://", verbose_name="Site internet"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsiae",
            name="website",
            field=models.URLField(blank=True, verbose_name="Site internet"),
        ),
        migrations.AlterField(
            model_name="siae",
            name="contact_social_website",
            field=models.URLField(
                blank=True, help_text="Doit commencer par http:// ou https://", verbose_name="Réseau social"
            ),
        ),
        migrations.AlterField(
            model_name="siae",
            name="contact_website",
            field=models.URLField(
                blank=True, help_text="Doit commencer par http:// ou https://", verbose_name="Site internet"
            ),
        ),
        migrations.AlterField(
            model_name="siae",
            name="website",
            field=models.URLField(blank=True, verbose_name="Site internet"),
        ),
        migrations.AlterField(
            model_name="siaegroup",
            name="contact_social_website",
            field=models.URLField(
                blank=True, help_text="Doit commencer par http:// ou https://", verbose_name="Réseau social"
            ),
        ),
        migrations.AlterField(
            model_name="siaegroup",
            name="contact_website",
            field=models.URLField(
                blank=True, help_text="Doit commencer par http:// ou https://", verbose_name="Site internet"
            ),
        ),
    ]
