# Generated by Django 5.1.6 on 2025-09-02 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0090_alter_historicalsiae_contact_social_website_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiaeESUS",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "siren",
                    models.CharField(
                        max_length=9,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(9)],
                        verbose_name="SIREN",
                    ),
                ),
            ],
        ),
    ]
