# Generated by Django 5.1.11 on 2025-10-09 10:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("siaes", "0091_siaeesus"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date de modification")),
                (
                    "siae",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="siaes.siae", verbose_name="Structure"
                    ),
                ),
            ],
            options={
                "verbose_name": "Structure en favoris",
                "verbose_name_plural": "Structures en favoris",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FavoriteList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date de modification")),
                (
                    "siaes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favorite_lists",
                        through="favorites.FavoriteItem",
                        to="siaes.siae",
                        verbose_name="Structures en favoris",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_lists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liste de favoris",
                "verbose_name_plural": "Listes de favoris",
            },
        ),
        migrations.AddField(
            model_name="favoriteitem",
            name="favorite_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="favorites.favoritelist",
                verbose_name="Liste de favoris",
            ),
        ),
        migrations.AddConstraint(
            model_name="favoriteitem",
            constraint=models.UniqueConstraint(fields=("siae", "favorite_list"), name="unique_favorite_item"),
        ),
    ]
