# Generated by Django 5.1.6 on 2025-08-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0003_favoritelist_siaes"),
        ("siaes", "0090_alter_historicalsiae_contact_social_website_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="favoriteitem",
            constraint=models.UniqueConstraint(fields=("siae", "favorite_list"), name="unique_favorite_item"),
        ),
    ]
