# Generated by Django 4.0.6 on 2022-08-09 12:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Code",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                ("code", models.CharField(max_length=8, verbose_name="Code")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date de modification")),
            ],
            options={
                "verbose_name": "Code CPV",
                "verbose_name_plural": "Code CPV",
                "ordering": ["code"],
            },
        ),
    ]
