# Generated by Django 4.0.6 on 2022-08-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sectors", "0003_sector_sectorgroup_ordering"),
        ("cpv", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="code",
            name="sectors",
            field=models.ManyToManyField(
                blank=True, related_name="cpv_codes", to="sectors.sector", verbose_name="Secteurs d'activité"
            ),
        ),
    ]
