STATUS_SENT = "SENT"
STATUS_SUBMITTED = "SUBMITTED"
STATUS_PUBLISHED = "PUBLISHED"
STATUS_REJECTED = "REJECTED"

STATUS_CHOICES = (
    (STATUS_SENT, "Invitation envoyée"),
    (STATUS_SUBMITTED, "Soumis, en attente de validation"),
    (STATUS_PUBLISHED, "Publié"),
    (STATUS_REJECTED, "Rejeté"),
)

STATUS_LIST = [s[0] for s in STATUS_CHOICES]

MAX_PUBLISHED = 3
MAX_PER_WEEK = 10
TOKEN_EXPIRY_DAYS = 30
CONTENT_MAX_LENGTH = 500

BREVO_TESTIMONIAL_REQUEST_TEMPLATE_CODE = "TESTIMONIAL_REQUEST"
BREVO_TESTIMONIAL_RECEIVED_TEMPLATE_CODE = "TESTIMONIAL_RECEIVED"
