SLUG_MAPPING_SOURCE_USER_PROPOSED = "user_proposed"
SLUG_MAPPING_SOURCE_ADMIN_VALIDATED = "admin_validated"
SLUG_MAPPING_SOURCE_AUTO_TRIGRAM = "auto_trigram"

SLUG_MAPPING_SOURCE_CHOICES = [
    (SLUG_MAPPING_SOURCE_USER_PROPOSED, "Proposé par un utilisateur"),
    (SLUG_MAPPING_SOURCE_ADMIN_VALIDATED, "Validé par un administrateur"),
    (SLUG_MAPPING_SOURCE_AUTO_TRIGRAM, "Résolu automatiquement (trigram)"),
]

SLUG_MAPPING_KIND_SECTOR = "sector"
SLUG_MAPPING_KIND_PERIMETER = "perimeter"
SLUG_MAPPING_KIND_COLUMN_HEADER = "column_header"

SLUG_MAPPING_KIND_CHOICES = [
    (SLUG_MAPPING_KIND_SECTOR, "Secteur d'activité"),
    (SLUG_MAPPING_KIND_PERIMETER, "Périmètre géographique"),
    (SLUG_MAPPING_KIND_COLUMN_HEADER, "En-tête de colonne"),
]

SLUG_MAPPING_CONFIDENCE_AUTO = 0.6
SLUG_MAPPING_CONFIDENCE_MIN = 0.2
SLUG_MAPPING_CONFIDENCE_TITLE_MIN = 0.4
