# Generated by Django 5.2.8 on 2025-11-25 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sectors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rome",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name="code ROME")),
                ("name", models.CharField(db_index=True, max_length=255, verbose_name="nom")),
            ],
            options={
                "verbose_name": "ROME",
                "verbose_name_plural": "ROME",
            },
        ),
        migrations.CreateModel(
            name="Appellation",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name="code")),
                ("name", models.CharField(db_index=True, max_length=255, verbose_name="nom")),
                (
                    "sectors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Secteurs d'activité concernés par ce poste",
                        related_name="appellations",
                        to="sectors.sector",
                        verbose_name="Secteurs d'activité",
                    ),
                ),
                (
                    "rome",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appellations",
                        to="jobs.rome",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
