# Generated by Django 5.1.6 on 2025-07-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchase",
            options={"ordering": ["created_at"], "verbose_name": "Achat", "verbose_name_plural": "Achats"},
        ),
    ]
