# Generated by Django 5.1.11 on 2025-09-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0008_company_labels"),
        ("purchases", "0002_alter_purchase_options"),
        ("siaes", "0090_alter_historicalsiae_contact_social_website_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(fields=["purchase_category"], name="purchases_p_purchas_75c0c7_idx"),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(fields=["buying_entity"], name="purchases_p_buying__e096ac_idx"),
        ),
    ]
