# Generated by Django 4.0.7 on 2022-08-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tracker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("v", models.PositiveIntegerField(verbose_name="Version")),
                ("timestamp", models.DateTimeField(verbose_name="Timestamp (UNIX Epoch)")),
                ("order", models.PositiveIntegerField()),
                ("env", models.CharField(max_length=200)),
                ("session_id", models.UUIDField(verbose_name="browser session UUID")),
                ("page", models.CharField(max_length=200)),
                ("action", models.CharField(max_length=200, verbose_name="Type d'action")),
                ("meta", models.JSONField()),
            ],
        ),
    ]
