# Generated by Django 5.1.11 on 2025-10-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StatsUser",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        db_index=True, primary_key=True, serialize=False, verbose_name="ID app leMarche"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Adresse e-mail")),
                ("first_name", models.CharField(max_length=150, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=150, verbose_name="Nom")),
                ("kind", models.CharField(blank=True, max_length=20, verbose_name="Type d'utilisateur")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="Téléphone")),
                ("company_name", models.CharField(blank=True, max_length=255, verbose_name="Nom de l'entreprise")),
                ("position", models.CharField(blank=True, max_length=255, verbose_name="Poste")),
                ("partner_kind", models.CharField(blank=True, max_length=20, verbose_name="Type de partenaire")),
            ],
            options={
                "db_table": "stats_user",
            },
        ),
        migrations.CreateModel(
            name="Tracker",
            fields=[
                ("id_internal", models.AutoField(primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(verbose_name="Version")),
                ("date_created", models.DateTimeField(verbose_name="Timestamp (UNIX Epoch)")),
                ("env", models.CharField(max_length=200)),
                ("source", models.CharField(max_length=200)),
                ("page", models.CharField(max_length=200)),
                ("action", models.CharField(max_length=200, verbose_name="Type d'action")),
                ("data", models.JSONField()),
                ("user_id", models.IntegerField(blank=True, null=True)),
                (
                    "user_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SIAE", "Structure"),
                            ("BUYER", "Acheteur"),
                            ("PARTNER", "Partenaire"),
                            ("INDIVIDUAL", "Particulier"),
                            ("ADMIN", "Administrateur"),
                        ],
                        max_length=20,
                    ),
                ),
                ("isadmin", models.BooleanField(default=False)),
                ("siae_id", models.IntegerField(blank=True, null=True)),
                (
                    "siae_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EI", "Entreprise d'insertion (EI)"),
                            ("AI", "Association intermédiaire (AI)"),
                            ("ACI", "Atelier chantier d'insertion (ACI)"),
                            ("ETTI", "Entreprise de travail temporaire d'insertion (ETTI)"),
                            ("EITI", "Entreprise d'insertion par le travail indépendant (EITI)"),
                            ("GEIQ", "Groupement d'employeurs pour l'insertion et la qualification (GEIQ)"),
                            ("SEP", "Produits et services réalisés en prison (SEP)"),
                            ("EA", "Entreprise adaptée (EA)"),
                            ("EATT", "Entreprise adaptée de travail temporaire (EATT)"),
                            ("ESAT", "Etablissement et service d'aide par le travail (ESAT)"),
                        ],
                        max_length=6,
                    ),
                ),
                ("siae_contact_email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "db_table": "trackers",
            },
        ),
    ]
