# Generated by Django 5.2.12 on 2026-03-12 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name="StatsUser",
                ),
            ],
        )
    ]
