# Generated by Django 5.2.11 on 2026-03-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statsuser",
            name="anonymized_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'anonymisation"),
        ),
    ]
