# Generated by Django 5.2.12 on 2026-03-12 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0002_delete_statsuser"),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE stats_user"),
    ]
