# Generated by Django 4.0.7 on 2022-10-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_statsuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tracker",
            name="session_id",
        ),
    ]
