# Generated by Django 4.1.2 on 2022-10-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0003_remove_tracker_session_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tracker",
            name="send_order",
        ),
    ]
