# Generated by Django 4.1.3 on 2022-12-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0004_remove_tracker_send_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracker",
            name="user_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tracker",
            name="user_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SIAE", "Structure"),
                    ("BUYER", "Acheteur"),
                    ("PARTNER", "Partenaire"),
                    ("ADMIN", "Administrateur"),
                ],
                max_length=20,
            ),
        ),
    ]
