# Generated by Django 4.1.3 on 2022-12-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0005_tracker_user_id_tracker_user_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracker",
            name="siae_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
