# Generated by Django 4.2.2 on 2023-12-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0007_tracker_siae_kind_and_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracker",
            name="user_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SIAE", "Structure"),
                    ("BUYER", "Acheteur"),
                    ("PARTNER", "Partenaire"),
                    ("INDIVIDUAL", "Particulier"),
                    ("ADMIN", "Administrateur"),
                ],
                max_length=20,
            ),
        ),
    ]
