# Generated by Django 4.0.2 on 2022-03-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perimeters", "0004_alter_perimeter_post_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perimeter",
            name="kind",
            field=models.CharField(
                choices=[
                    ("CITY", "Commune"),
                    ("DEPARTMENT", "Département"),
                    ("REGION", "Région"),
                    ("COUNTRY", "Pays"),
                ],
                max_length=20,
                verbose_name="Type de périmètre",
            ),
        ),
    ]
