# Generated by Django 4.0.4 on 2022-04-13 08:10

from django.db import migrations, models

import lemarche.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("perimeters", "0004_alter_perimeter_post_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perimeter",
            name="post_codes",
            field=lemarche.utils.fields.ChoiceArrayField(
                base_field=models.CharField(max_length=5),
                blank=True,
                default=list,
                size=None,
                verbose_name="Codes postaux",
            ),
        ),
    ]
