# Generated by Django 5.2.11 on 2026-03-03 14:17

from django.db import migrations


def create_user_deletion_template(apps, schema_editor):
    TemplateTransactional = apps.get_model("conversations", "TemplateTransactional")

    template = {
        "name": "Avertissement de suppression de compte utilisateur",
        "code": "USER_DELETION_WARNING",
        "description": "Envoyé à l'utilisateur pour le notifier que son compte sera supprimé dans un mois "
        "s'il ne se connecte pas",
    }

    TemplateTransactional.objects.create(**template)


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0002_populate"),
    ]

    operations = [migrations.RunPython(create_user_deletion_template, reverse_code=migrations.RunPython.noop)]
