# Generated by Django 5.2.11 on 2026-03-03 14:17

from django.db import migrations


def create_user_deletion_template(apps, schema_editor):
    TemplateTransactional = apps.get_model("conversations", "TemplateTransactional")

    template = {
        "name": "Avertissement de suppression de compte utilisateur",
        "code": "USER_DELETION_WARNING",
        "description": """
        Bonjour {{ params.user_full_name }}, votre compte sera supprimé le {{ params.deletion_date }}
         si vous ne vous connectez pas avant.
        Bonne journée,
        L'équipe du marché de l'inclusion
        """,
    }

    TemplateTransactional.objects.create(**template)


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0002_populate"),
    ]

    operations = [migrations.RunPython(create_user_deletion_template, reverse_code=migrations.RunPython.noop)]
