# Generated by Django 4.2.2 on 2023-07-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0002_conversation_email_sender_conversation_kind_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"verbose_name": "Conversation"},
        ),
        migrations.AlterField(
            model_name="conversation",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Objet de la première demande"),
        ),
    ]
