# Generated by Django 4.2.2 on 2023-08-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0002_conversation_kind_conversation_siae_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"verbose_name": "Conversation"},
        ),
        migrations.AddField(
            model_name="conversation",
            name="email_sender",
            field=models.EmailField(
                max_length=254, null=True, verbose_name="Email de l'initiateur de la conversation"
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="title",
            field=models.CharField(default="test", max_length=200, verbose_name="Objet de la première demande"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="conversation",
            name="data",
            field=models.JSONField(default=list),
        ),
    ]
