# Generated by Django 4.2.2 on 2023-08-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0003_alter_conversation_options_conversation_email_sender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="initial_body_message",
            field=models.TextField(blank=True, verbose_name="Message initial"),
        ),
    ]
