# Generated by Django 4.2.2 on 2023-08-03 09:32

from django.db import migrations
from django_extensions.db.fields import ShortUUIDField
from shortuuid import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0004_conversation_initial_body_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="uuid",
        ),
        migrations.AddField(
            model_name="conversation",
            name="uuid",
            field=ShortUUIDField(
                auto_created=True,
                blank=True,
                db_index=True,
                default=uuid,
                editable=False,
                unique=True,
                verbose_name="Identifiant UUID",
            ),
        ),
    ]
