# Generated by Django 4.2.2 on 2023-08-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0005_remove_conversation_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="email_sender",
            new_name="sender_email",
        ),
    ]
