# Generated by Django 4.2.2 on 2023-08-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0006_rename_email_sender_conversation_sender_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="sender_first_name",
            field=models.CharField(default="Le marché", max_length=150, verbose_name="Prénom"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conversation",
            name="sender_last_name",
            field=models.CharField(default="de l'inclusion", max_length=150, verbose_name="Nom"),
            preserve_default=False,
        ),
    ]
