# Generated by Django 4.2.2 on 2023-08-30 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("conversations", "0007_conversation_sender_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="sender_user",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur à l'initiative",
            ),
        ),
    ]
