# Generated by Django 4.2.2 on 2023-09-05 18:03

import random

from django.db import migrations, models


def set_uuids(apps, schema_editor):
    Conversation = apps.get_model("conversations", "Conversation")
    for conversation in Conversation.objects.all():
        siae = conversation.siae
        conversation.uuid_sender = (
            f"{conversation.sender_first_name}_{conversation.sender_last_name}_{random.randint(100, 10000)}"
        )
        conversation.uuid_siae = f"{siae.contact_first_name}_{siae.contact_last_name}_{random.randint(100, 10000)}"
        conversation.save()


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0009_conversation_validated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="uuid_sender",
            field=models.CharField(db_index=True, default="", max_length=255, verbose_name="Identifiant initiateur"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conversation",
            name="uuid_siae",
            field=models.CharField(db_index=True, default="", max_length=255, verbose_name="Identifiant structure"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="conversation",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="Version"),
        ),
        migrations.RunPython(set_uuids, migrations.RunPython.noop),
    ]
