# Generated by Django 4.2.2 on 2023-09-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0010_conversation_uuid_sender_conversation_uuid_siae_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="uuid_sender",
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name="Identifiant initiateur"),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="uuid_siae",
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name="Identifiant structure"),
        ),
    ]
