# Generated by Django 4.2.2 on 2023-09-05 18:03
from django.db import migrations


def set_uuids_again(apps, schema_editor):
    Conversation = apps.get_model("conversations", "Conversation")
    for conversation in Conversation.objects.filter(version=0):
        conversation.sender_encoded = ""
        conversation.set_sender_encoded()
        conversation.siae_encoded = ""
        conversation.set_siae_encoded()
        conversation.save()


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0011_conversation_sender_siae_encoded_unique"),
    ]

    operations = [
        migrations.RunPython(set_uuids_again, migrations.RunPython.noop),
    ]
