# Generated by Django 4.2.2 on 2023-12-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0012_templatetransactional"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatetransactional",
            name="email_from_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="E-mail : expéditeur (e-mail)"
            ),
        ),
        migrations.AddField(
            model_name="templatetransactional",
            name="email_from_name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="E-mail : expéditeur (nom)"),
        ),
        migrations.AddField(
            model_name="templatetransactional",
            name="email_subject",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="E-mail : objet"),
        ),
    ]
