# Generated by Django 4.2.2 on 2023-12-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0012_templatetransactional"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatetransactional",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Actif"),
        ),
        migrations.AddField(
            model_name="templatetransactional",
            name="source",
            field=models.CharField(
                blank=True, choices=[("MAILJET", "Mailjet"), ("BREVO", "Brevo")], max_length=20, verbose_name="Source"
            ),
        ),
    ]
