# Generated by Django 4.2.9 on 2024-04-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0013_templatetransactional_email_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatetransactional",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("MAILJET", "Mailjet"), ("BREVO", "Brevo"), ("DJANGO", "Django")],
                max_length=20,
                verbose_name="Source",
            ),
        ),
    ]
