# Generated by Django 4.2.13 on 2024-07-15 10:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("conversations", "0015_remove_templatetransactional_email_from_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateTransactionalSendLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date de modification")),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "template_transactional",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="send_logs",
                        to="conversations.templatetransactional",
                        verbose_name="Template transactionnel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template transactionnel: logs d'envois",
                "verbose_name_plural": "Templates transactionnels: logs d'envois",
            },
        ),
    ]
