# Generated by Django 4.2.15 on 2024-12-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0017_emailgroup_disabledemail_templatetransactional_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="is_anonymized",
            field=models.BooleanField(default=False, verbose_name="Est anonymisé"),
        ),
    ]
