# Generated by Django 4.2.15 on 2025-01-13 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0018_conversation_is_anonymized"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templatetransactional",
            name="mailjet_id",
        ),
        migrations.RemoveField(
            model_name="templatetransactional",
            name="source",
        ),
    ]
