# Generated by Django 5.1.6 on 2025-06-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0023_missing_transac_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatetransactional",
            name="code",
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name="Nom technique"),
        ),
    ]
