# Generated by Django 5.1.6 on 2025-06-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0024_alter_templatetransactional_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatetransactional",
            name="tally_brevo_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, unique=True, verbose_name="Identifiant Brevo Tally"
            ),
        ),
    ]
