# Generated by Django 3.2.1 on 2021-06-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20210602_0928"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siae",
            options={"ordering": ["name"]},
        ),
    ]
