# Generated by Django 3.2.8 on 2021-10-24 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_migrate_siae_model_to_siae_app"),
        ("siaes", "0005_alter_siae_sectors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectorstring",
            name="translatable",
        ),
        migrations.DeleteModel(
            name="Sector",
        ),
        migrations.DeleteModel(
            name="SectorString",
        ),
    ]
