# Generated by Django 5.1.11 on 2025-10-09 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                ("brand", models.CharField(blank=True, max_length=255, verbose_name="Enseigne")),
                ("website", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date de modification")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                ("logo_url", models.URLField(blank=True, max_length=500, verbose_name="Lien vers le logo")),
            ],
            options={
                "verbose_name": "Réseau",
                "verbose_name_plural": "Réseaux",
            },
        ),
    ]
