# Generated by Django 3.2.7 on 2021-09-08 14:32

from django.db import migrations
from django.utils.text import slugify


def slugify_name(apps, schema_editor):
    Network = apps.get_model("networks", "Network")
    for network in Network.objects.all():
        network.slug = slugify(network.name)
        network.save()


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0002_network_slug"),
    ]

    operations = [
        migrations.RunPython(slugify_name),
    ]
