# Generated by Django 4.1.7 on 2023-06-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0004_alter_network_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="network",
            name="logo_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="Lien vers le logo"),
        ),
    ]
