# Generated by Django 4.0.1 on 2022-02-16 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sectors", "0003_sector_sectorgroup_ordering"),
        ("perimeters", "0004_alter_perimeter_post_codes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tender",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("EMAIL", "Téléphone"), ("EMAIL", "Lien externe")],
                        default="TENDER",
                        max_length=6,
                        verbose_name="Type de besoin",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Raison sociale")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("constraints", models.TextField(blank=True, verbose_name="Contraintes techniques spécifiques")),
                ("completion_time", models.TextField(blank=True, verbose_name="Délais de réalisation / Fréquence")),
                ("external_link", models.URLField(blank=True, verbose_name="Lien externe")),
                (
                    "kind_response",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("EMAIL", "Téléphone"), ("EMAIL", "Lien externe")],
                        default="TENDER",
                        max_length=6,
                        verbose_name="Comment répondre",
                    ),
                ),
                (
                    "perimeter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="perimeters.perimeter",
                        verbose_name="Lieu d'exécution",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sectors.sector",
                        verbose_name="Secteur d'activité",
                    ),
                ),
            ],
        ),
    ]
