# Generated by Django 4.0.1 on 2022-03-02 16:22

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("perimeters", "0004_alter_perimeter_post_codes"),
        ("sectors", "0003_sector_sectorgroup_ordering"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tender",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("TENDER", "Appel d'offre"), ("QUOTE", "Devis")],
                        default="TENDER",
                        max_length=6,
                        verbose_name="Type de besoin",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("constraints", models.TextField(blank=True, verbose_name="Contraintes techniques spécifiques")),
                ("completion_time", models.TextField(blank=True, verbose_name="Délais de réalisation / Fréquence")),
                ("external_link", models.URLField(blank=True, verbose_name="Lien externe")),
                ("deadline_date", models.DateField(verbose_name="Date de clôture des réponses")),
                (
                    "start_working_date",
                    models.DateField(blank=True, null=True, verbose_name="Date idéale de début des prestations"),
                ),
                ("contact_first_name", models.CharField(blank=True, max_length=255, verbose_name="Prénom du contact")),
                (
                    "contact_last_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Nom de famille du contact"),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254, verbose_name="Email du contact")),
                ("contact_phone", models.CharField(blank=True, max_length=20, verbose_name="Téléphone du contact")),
                (
                    "response_kind",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[("EMAIL", "Email"), ("EMAIL", "Téléphone"), ("EMAIL", "Lien externe")],
                            max_length=6,
                        ),
                        size=None,
                        verbose_name="Comment répondre",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date de modification")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perimeters",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tenders",
                        to="perimeters.Perimeter",
                        verbose_name="Lieux d'exécutions",
                    ),
                ),
                (
                    "sectors",
                    models.ManyToManyField(
                        blank=True, related_name="tenders", to="sectors.Sector", verbose_name="Secteurs d'activités"
                    ),
                ),
            ],
            options={
                "verbose_name": "Besoin d'acheteur",
                "verbose_name_plural": "Besoins des acheteurs",
                "ordering": ["deadline_date"],
            },
        ),
    ]
