# Generated by Django 4.0.2 on 2022-03-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="nb_siaes_found",
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre de SIAE trouvées"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="kind",
            field=models.CharField(
                choices=[("TENDER", "Appel d'offre"), ("QUOTE", "Devis"), ("PROJ", "Projet d’achat")],
                default="TENDER",
                max_length=6,
                verbose_name="Type de besoin",
            ),
        ),
    ]
