# Generated by Django 5.2.8 on 2025-12-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sectors", "0001_initial"),
        ("tenders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="sectors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Sélectionnez un ou plusieurs secteurs d'activité",
                related_name="tenders",
                to="sectors.sector",
                verbose_name="Secteurs d'activité",
            ),
        ),
    ]
