# Generated by Django 4.0.1 on 2022-03-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="kind",
            field=models.CharField(
                choices=[("TENDER", "Appel d'offre"), ("QUOTE", "Devis"), ("PROJ", "Projet d’achat")],
                default="TENDER",
                max_length=6,
                verbose_name="Type de besoin",
            ),
        ),
    ]
