# Generated by Django 4.0.1 on 2022-03-07 16:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="amount",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Montant du marché"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="response_kind",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("EMAIL", "Email"), ("TEL", "Téléphone"), ("EXTERN", "Lien externe")], max_length=6
                ),
                size=None,
                verbose_name="Comment répondre",
            ),
        ),
    ]
