# Generated by Django 4.0.2 on 2022-03-18 09:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sectors", "0003_sector_sectorgroup_ordering"),
        ("perimeters", "0004_alter_perimeter_post_codes"),
        ("tenders", "0002_tender_nb_siaes_found_alter_tender_kind"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tender",
            old_name="nb_siaes_found",
            new_name="siae_found_count",
        ),
        migrations.AlterField(
            model_name="tender",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-mail du contact"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="external_link",
            field=models.URLField(blank=True, verbose_name="Lien vers l'appel d'offre"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="kind",
            field=models.CharField(
                choices=[("TENDER", "Appel d'offre"), ("QUOTE", "Devis"), ("PROJ", "Projet d'achat")],
                default="TENDER",
                max_length=6,
                verbose_name="Type de besoin",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="perimeters",
            field=models.ManyToManyField(
                related_name="tenders", to="perimeters.Perimeter", verbose_name="Lieux d'exécution"
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="response_kind",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("EMAIL", "E-mail"), ("TEL", "Téléphone"), ("EXTERN", "Lien externe")], max_length=6
                ),
                size=None,
                verbose_name="Comment souhaitez-vous être contacté ?",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="sectors",
            field=models.ManyToManyField(
                related_name="tenders", to="sectors.Sector", verbose_name="Secteurs d'activité"
            ),
        ),
    ]
