# Generated by Django 4.0.2 on 2022-03-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0002_alter_tender_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="nb_siaes_found",
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre de SIAE trouvées"),
        ),
    ]
