# Generated by Django 4.0.1 on 2022-02-23 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0002_tender_deadline_date_tender_start_working_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
        ),
        migrations.AddField(
            model_name="tender",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Date de modification"),
        ),
    ]
