# Generated by Django 4.0.2 on 2022-03-28 13:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0053_siae_contact_social_website_and_more"),
        ("tenders", "0003_rename_nb_siaes_found_tender_siae_found_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenderSiae",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source",
                    models.CharField(
                        choices=[("EMAIL", "E-mail"), ("DASHBOARD", "Dashboard")], default="EMAIL", max_length=20
                    ),
                ),
                (
                    "email_send_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi de l'e-mail"),
                ),
                (
                    "detail_display_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de visualisation du besoin"),
                ),
                (
                    "contact_click_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de clic sur les coordonnées du besoin"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date de modification")),
                (
                    "siae",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="siaes.siae", verbose_name="Structure"
                    ),
                ),
            ],
            options={
                "verbose_name": "Structure correspondant au besoin",
                "verbose_name_plural": "Structures correspondantes au besoin",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="tender",
            name="siaes",
            field=models.ManyToManyField(
                blank=True,
                related_name="siaes",
                through="tenders.TenderSiae",
                to="siaes.Siae",
                verbose_name="Structures correspondantes au besoin",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="siae_found_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre de structures trouvées"),
        ),
        migrations.AddField(
            model_name="tendersiae",
            name="tender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenders.tender", verbose_name="Besoin d'acheteur"
            ),
        ),
    ]
