# Generated by Django 4.0.2 on 2022-04-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0006_alter_tender_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="kind",
            field=models.CharField(
                choices=[("TENDER", "Appel d'offre"), ("QUOTE", "Devis"), ("PROJ", "Sourcing")],
                default="TENDER",
                max_length=6,
                verbose_name="Type de besoin",
            ),
        ),
    ]
