# Generated by Django 4.0.2 on 2022-04-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0008_alter_tender_author_alter_tender_response_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="validated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de validation"),
        ),
    ]
