# Generated by Django 4.0.4 on 2022-05-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0009_tender_validated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="external_link",
            field=models.URLField(blank=True, verbose_name="Lien vers l'appel d'offres"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="kind",
            field=models.CharField(
                choices=[("TENDER", "Appel d'offres"), ("QUOTE", "Devis"), ("PROJ", "Sourcing")],
                default="TENDER",
                max_length=6,
                verbose_name="Type de besoin",
            ),
        ),
    ]
