# Generated by Django 4.0.2 on 2022-04-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perimeters", "0005_alter_perimeter_post_codes"),
        ("tenders", "0009_tender_validated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="is_country_area",
            field=models.BooleanField(default=False, verbose_name="France entière"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="perimeters",
            field=models.ManyToManyField(
                blank=True, related_name="tenders", to="perimeters.Perimeter", verbose_name="Lieux d'exécution"
            ),
        ),
    ]
