# Generated by Django 4.0.4 on 2022-05-16 14:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perimeters", "0005_alter_perimeter_post_codes"),
        ("tenders", "0011_merge_20220512_1802"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerShareTender",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, verbose_name="Nom du partenaire")),
                (
                    "amount_in",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("<25K", "0-25K €"),
                            ("<100K", "25K-100K €"),
                            ("<1M", "100K-1M €"),
                            ("<5M", "1M-5M €"),
                            (">5M", "> 5M €"),
                        ],
                        max_length=9,
                        null=True,
                        verbose_name="Montant du marché",
                    ),
                ),
                (
                    "contact_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=255), size=None, verbose_name="Liste de contact"
                    ),
                ),
                (
                    "perimeters",
                    models.ManyToManyField(
                        blank=True,
                        related_name="partners_share_tenders",
                        to="perimeters.perimeter",
                        verbose_name="Lieux de filtrage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partenaire intéressé des dépôts de besoins",
                "verbose_name_plural": "Partenaires intéressés des dépôts de besoins",
            },
        ),
    ]
