# Generated by Django 4.0.4 on 2022-06-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0012_partnersharetender"),
        ("tenders", "0012_tender_siae_interested_list_last_seen_date"),
    ]

    operations = []
