# Generated by Django 4.0.4 on 2022-05-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0012_partnersharetender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnersharetender",
            name="amount_in",
            field=models.CharField(
                blank=True,
                choices=[
                    ("<25K", "0-25K €"),
                    ("<100K", "25K-100K €"),
                    ("<1M", "100K-1M €"),
                    ("<5M", "1M-5M €"),
                    (">5M", "> 5M €"),
                ],
                max_length=9,
                null=True,
                verbose_name="Montant du marché limite",
            ),
        ),
    ]
