# Generated by Django 4.0.4 on 2022-06-08 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0013_partnersharetender"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnersharetender",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
        ),
        migrations.AddField(
            model_name="partnersharetender",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Date de modification"),
        ),
    ]
