# Generated by Django 4.0.4 on 2022-06-08 08:24

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0014_partnersharetender_timestamps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnersharetender",
            name="contact_email_list",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.EmailField(max_length=255),
                blank=True,
                default=list,
                size=None,
                verbose_name="Liste de contact",
            ),
        ),
    ]
