# Generated by Django 4.0.6 on 2022-07-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0017_tender_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnersharetender",
            name="logs",
            field=models.JSONField(default=list, editable=False, verbose_name="Logs historiques"),
        ),
    ]
