# Generated by Django 4.0.6 on 2022-07-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0018_partnersharetender_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="source",
            field=models.CharField(blank=True, max_length=20, verbose_name="Source"),
        ),
    ]
