# Generated by Django 4.0.6 on 2022-08-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0019_tender_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="accept_share_amount",
            field=models.BooleanField(
                default=False,
                help_text="Je souhaite partager ce montant aux partenaires recevant mon besoin",
                verbose_name="Partage du montant du marché",
            ),
        ),
        migrations.AlterField(
            model_name="partnersharetender",
            name="amount_in",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0-1K", "0-1000 €"),
                    ("1-5K", "1000-5K €"),
                    ("5-10K", "5K-10K €"),
                    ("10-15K", "10K-15K €"),
                    ("15-20K", "15K-20K €"),
                    ("20-30K", "20K-30K €"),
                    ("30-50K", "30K-50K €"),
                    ("50-100K", "50K-100K €"),
                    ("100-150K", "100K-150K €"),
                    ("100-250K", "100K-250K €"),
                    ("250-500K", "250K-500K €"),
                    ("500-750K", "500K-750K €"),
                    ("750K-1M", "750K-1M €"),
                    (">1M", "> 1M €"),
                ],
                max_length=9,
                null=True,
                verbose_name="Montant du marché limite",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="amount",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0-1K", "0-1000 €"),
                    ("1-5K", "1000-5K €"),
                    ("5-10K", "5K-10K €"),
                    ("10-15K", "10K-15K €"),
                    ("15-20K", "15K-20K €"),
                    ("20-30K", "20K-30K €"),
                    ("30-50K", "30K-50K €"),
                    ("50-100K", "50K-100K €"),
                    ("100-150K", "100K-150K €"),
                    ("100-250K", "100K-250K €"),
                    ("250-500K", "250K-500K €"),
                    ("500-750K", "500K-750K €"),
                    ("750K-1M", "750K-1M €"),
                    (">1M", "> 1M €"),
                ],
                max_length=9,
                null=True,
                verbose_name="Montant du marché",
            ),
        ),
    ]
