# Generated by Django 4.0.7 on 2022-09-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0021_tender_amount_choices_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="accept_share_amount",
            field=models.BooleanField(
                default=False,
                help_text="Je souhaite partager ce montant aux partenaires recevant mon besoin",
                verbose_name="Partage du montant du marché",
            ),
        ),
    ]
