# Generated by Django 4.0.7 on 2022-10-04 12:34

from django.db import migrations, models


def init_existing_accept_contact_share_to_true(apps, schema_editor):
    TenderSiae = apps.get_model("tenders", "TenderSiae")
    TenderSiae.objects.filter(contact_click_date__isnull=False).update(accept_contact_share=True)


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0023_alter_partnersharetender_amount_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tendersiae",
            name="accept_contact_share",
            field=models.BooleanField(default=False, verbose_name="Partage des informations de contact à l'acheteur"),
        ),
        migrations.RunPython(init_existing_accept_contact_share_to_true),
    ]
