# Generated by Django 4.0.7 on 2022-10-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0024_tender_accept_cocontracting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="source",
            field=models.CharField(
                choices=[
                    ("FORM", "Formulaire"),
                    ("FORM_CSRF", "Formulaire (erreur CSRF)"),
                    ("STAFF_C4_CREATED", "Staff C4"),
                ],
                default="FORM",
                max_length=20,
                verbose_name="Source",
            ),
        ),
    ]
