# Generated by Django 4.0.7 on 2022-10-12 15:03

from django.db import migrations, models

import lemarche.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0026_tender_is_marche_useful_tender_marche_benefits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="marche_benefits",
            field=lemarche.utils.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("TIME", "Gagner du temps"),
                        ("DISCOVER", "Découvrir de nouveaux prestataires inclusifs"),
                        ("MORE", "Faire plus d'achats inclusifs"),
                        ("CLAUSE", "Intégrer une clause sociale à un marché"),
                        ("SECURE", "Sécuriser un marché réservé"),
                        ("NONE", "Aucun"),
                    ],
                    max_length=20,
                ),
                blank=True,
                default=list,
                help_text="Quels sont le(s) bénéfice(s) de passer par le Marché de l'inclusion pour ce besoin ?",
                size=None,
                verbose_name="Bénéfices du marché de l'inclusion",
            ),
        ),
    ]
