# Generated by Django 4.0.8 on 2022-10-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0027_alter_tender_marche_benefits"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tender",
            options={
                "ordering": ["-created_at", "deadline_date"],
                "verbose_name": "Besoin d'acheteur",
                "verbose_name_plural": "Besoins des acheteurs",
            },
        ),
    ]
