# Generated by Django 4.0.8 on 2022-10-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0028_alter_tender_options_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tendersiae",
            name="source",
            field=models.CharField(
                choices=[("EMAIL", "E-mail"), ("DASHBOARD", "Dashboard"), ("LINK", "Lien")],
                default="EMAIL",
                max_length=20,
            ),
        ),
    ]
