# Generated by Django 4.1.2 on 2022-11-14 11:07

from django.db import migrations, models

import lemarche.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0030_tender_siae_kind_alter_tender_presta_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="accept_cocontracting",
            field=models.BooleanField(
                default=False,
                help_text="Ce besoin peut être répondu par plusieurs prestataires (co-traitance ou sous-traitance)",
                verbose_name="Ouvert à la co-traitance",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="marche_benefits",
            field=lemarche.utils.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("TIME", "Gagner du temps"),
                        ("DISCOVER", "Découvrir de nouveaux prestataires inclusifs"),
                        ("MORE", "Faire plus d'achats inclusifs"),
                        ("CLAUSE", "Intégrer une clause sociale à un marché"),
                        ("SECURE", "Sécuriser un marché réservé"),
                        ("NONE", "Aucun"),
                    ],
                    max_length=20,
                ),
                blank=True,
                default=list,
                help_text="Pour ce besoin, quels sont les bénéfices de passer par le Marché de l'inclusion ?",
                size=None,
                verbose_name="Bénéfices du marché de l'inclusion",
            ),
        ),
    ]
