# Generated by Django 4.1.2 on 2022-11-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0030_tender_siae_kind_alter_tender_presta_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="extra_data",
            field=models.JSONField(default=dict, editable=False, verbose_name="Données complémentaires"),
        ),
    ]
