# Generated by Django 4.1.3 on 2022-11-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0031_alter_tender_accept_cocontracting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="extra_data",
            field=models.JSONField(default=dict, editable=False, verbose_name="Données complémentaires"),
        ),
    ]
