# Generated by Django 4.1.3 on 2022-11-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0032_tender_extra_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="status",
            field=models.CharField(
                choices=[("1", "Brouillon"), ("2", "Publié"), ("3", "Validé")],
                default="1",
                max_length=1,
                verbose_name="Statut du dépôt de besoin",
            ),
        ),
    ]
