# Generated by Django 4.1.3 on 2022-11-30 10:42

from django.db import migrations, models


def set_marche_is_useful(apps, schema_editor):
    Tender = apps.get_model("tenders", "tender")

    Tender.objects.filter(is_marche_useful=True).update(is_marche_useful_2="0")
    Tender.objects.filter(is_marche_useful=False).update(is_marche_useful_2="3")


def set_marche_is_useful_reverse(apps, schema_editor):
    Tender = apps.get_model("tenders", "tender")

    Tender.objects.filter(is_marche_useful_2__in=["0", "1"]).update(is_marche_useful=True)
    Tender.objects.filter(is_marche_useful_2__in=["2", "3"]).update(is_marche_useful=False)


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0034_tender_siae_transactioned"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="is_marche_useful_2",
            field=models.CharField(
                choices=[("0", "Non"), ("1", "Peu probable"), ("3", "Très probable"), ("4", "Oui")],
                default="0",
                help_text="Si le Marché de l'inclusion n'existait pas, auriez-vous fait appel à des prestataires inclusifs pour ce besoin ?",  # noqa
                max_length=2,
                verbose_name="Utilité du marché de l'inclusion",
            ),
        ),
        migrations.RunPython(set_marche_is_useful, reverse_code=set_marche_is_useful_reverse),
        migrations.RemoveField(
            model_name="tender",
            name="is_marche_useful",
        ),
        migrations.RenameField(
            model_name="tender",
            old_name="is_marche_useful_2",
            new_name="is_marche_useful",
        ),
    ]
