# Generated by Django 4.1.3 on 2022-12-01 12:32

from django.db import migrations, models


def set_tender_status(apps, schema_editor):
    Tender = apps.get_model("tenders", "tender")

    Tender.objects.filter(models.Q(validated_at__isnull=False) or models.Q(tendersiae__isnull=False)).update(
        status="VALIDATED"
    )


def set_tender_status_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0035_tender_is_marche_useful_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Brouillon"), ("PUBLISHED", "Publié"), ("VALIDATED", "Validé")],
                default="DRAFT",
                max_length=10,
                verbose_name="Statut du dépôt de besoin",
            ),
        ),
        migrations.RunPython(set_tender_status, reverse_code=set_tender_status_reverse),
    ]
