# Generated by Django 4.1.3 on 2022-12-13 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perimeters", "0005_alter_perimeter_post_codes"),
        ("tenders", "0037_alter_tender_accept_share_amount_alter_tender_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="intervention_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tenders_location",
                to="perimeters.perimeter",
                verbose_name="Lieu d'intervention",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="perimeters",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ajoutez un ou plusieurs lieux d'exécutions",
                related_name="tenders",
                to="perimeters.perimeter",
                verbose_name="Périmètres ciblés",
            ),
        ),
    ]
