# Generated by Django 4.1.3 on 2022-12-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0038_tender_intervention_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tendersiae",
            old_name="contact_click_date",
            new_name="detail_contact_click_date",
        ),
    ]
