# Generated by Django 4.1.3 on 2022-12-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0039_tender_siae_rename_contact_click_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tendersiae",
            name="email_link_click_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de clic sur le lien dans l'e-mail"),
        ),
    ]
