# Generated by Django 4.1.3 on 2023-01-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0040_tendersiae_email_link_click_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Brouillon"), ("PUBLISHED", "Publié"), ("VALIDATED", "Validé")],
                default="DRAFT",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
    ]
