# Generated by Django 4.1.3 on 2023-01-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0040_tendersiae_email_link_click_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="why_amount_is_blank",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DONT_KNOW", "Je ne connais pas le montant de mon besoin pour le moment"),
                    ("DONT_WANT_TO_SHARE", "Je ne souhaite pas communiquer le montant"),
                ],
                max_length=18,
                null=True,
                verbose_name="Pourquoi le montant du besoin n'est pas renseigné ?",
            ),
        ),
    ]
