# Generated by Django 4.2.2 on 2023-07-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0048_tender_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="amount_exact",
            field=models.PositiveIntegerField(
                blank=True, help_text="Champ renseigné par un ADMIN", null=True, verbose_name="Montant exact du besoin"
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="siae_transactioned",
            field=models.BooleanField(
                default=False,
                help_text="Champ renseigné par un ADMIN",
                verbose_name="Abouti à une transaction avec une structure",
            ),
        ),
    ]
