# Generated by Django 4.2.2 on 2023-07-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0049_tender_amount_exact"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de publication"),
        ),
    ]
