# Generated by Django 4.2.2 on 2023-08-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0051_tender_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="real_incrementality",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(None, "Par défaut"), (0, "0%"), (15, "15%"), (75, "75%"), (100, "100%")],
                default=None,
                help_text="Champ renseigné par un ADMIN",
                null=True,
                verbose_name="Modification de l’incrémental (%)",
            ),
        ),
    ]
