# Generated by Django 4.2.2 on 2023-08-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0051_tender_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="incremental_custom",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=None,
                help_text="Champ renseigné par un ADMIN",
                null=True,
                verbose_name="Modification de l’incrémental (%)",
            ),
        ),
    ]
