# Generated by Django 4.2.2 on 2023-08-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0052_tender_incremental_custom"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="survey_transactioned_answer",
            field=models.BooleanField(blank=True, null=True, verbose_name="Sondage transaction J+30 : réponse"),
        ),
        migrations.AddField(
            model_name="tender",
            name="survey_transactioned_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Sondage transaction J+30 : date de réponse"
            ),
        ),
    ]
