# Generated by Django 4.2.2 on 2023-09-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0053_tender_survey_transactioned_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="survey_transactioned_send_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Sondage transaction J+30 : date d'envoi de l'e-mail"
            ),
        ),
    ]
