# Generated by Django 4.2.2 on 2023-09-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0054_tender_survey_transactioned_send_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="contact_company_name",
            field=models.CharField(
                blank=True,
                help_text="Laisser vide pour afficher le nom de l'entreprise de l'auteur",
                max_length=255,
                verbose_name="Nom de l'entreprise du contact",
            ),
        ),
    ]
