# Generated by Django 4.2.2 on 2023-09-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0055_tender_contact_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="scale_marche_useless",
            field=models.CharField(
                choices=[("0", "Non"), ("1", "Peu probablement"), ("2", "Très probablement"), ("3", "Oui")],
                default="0",
                help_text=(
                    "Si le Marché de l'inclusion n'existait pas, auriez-vous "
                    "consulté des prestataires inclusifs* pour ce besoin ?"
                ),
                max_length=2,
                verbose_name="Utilité du marché de l'inclusion",
            ),
        ),
    ]
