# Generated by Django 4.2.2 on 2023-09-26 08:05

from django.db import migrations, models


def set_siae_transactioned_false_to_null(apps, schema_editor):
    Tender = apps.get_model("tenders", "Tender")
    for tender in Tender.objects.filter(siae_transactioned=False, survey_transactioned_answer=None):
        tender.siae_transactioned = None
        tender.save(update_fields=["siae_transactioned"])


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0056_alter_tender_scale_marche_useless"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="siae_transactioned",
            field=models.BooleanField(
                blank=True,
                help_text="Champ renseigné par un ADMIN",
                null=True,
                verbose_name="Abouti à une transaction avec une structure",
            ),
        ),
        migrations.RunPython(code=set_siae_transactioned_false_to_null),
    ]
