# Generated by Django 4.2.2 on 2023-10-05 14:15

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0057_alter_tender_siae_transactioned"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenderStepsData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "uuid",
                    django_extensions.db.fields.ShortUUIDField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        unique=True,
                        verbose_name="Identifiant UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date de modification")),
                ("steps_data", models.JSONField(default=list, editable=False, verbose_name="Données des étapes")),
            ],
        ),
    ]
