# Generated by Django 4.2.2 on 2023-10-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0057_alter_tender_siae_transactioned"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="siae_count",
            field=models.IntegerField(default=0, verbose_name="Nombre de structures concernées"),
        ),
    ]
