# Generated by Django 4.2.2 on 2023-10-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0058_tenderstepsdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="siae_count",
            field=models.IntegerField(
                default=0,
                help_text="Champ recalculé à intervalles réguliers",
                verbose_name="Nombre de structures concernées",
            ),
        ),
    ]
