# Generated by Django 4.2.5 on 2023-10-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0059_tender_siae_count_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="response_is_anonymous",
            field=models.BooleanField(default=False, verbose_name="Je souhaite rester anonyme"),
        ),
    ]
