# Generated by Django 4.2.2 on 2023-11-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0059_tender_siae_count_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="survey_transactioned_amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Sondage transaction : montant du besoin"
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="survey_transactioned_feedback",
            field=models.TextField(blank=True, verbose_name="Sondage transaction : retour d'expérience"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="survey_transactioned_answer",
            field=models.BooleanField(blank=True, null=True, verbose_name="Sondage transaction : réponse"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="survey_transactioned_answer_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Sondage transaction : date de réponse"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="survey_transactioned_send_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Sondage transaction : date d'envoi de l'e-mail"
            ),
        ),
    ]
