# Generated by Django 4.2.2 on 2023-11-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0061_tender_response_is_anonymous"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="kind",
            field=models.CharField(
                choices=[("TENDER", "Appel d'offres"), ("QUOTE", "Demande de devis"), ("PROJ", "Sourcing")],
                default="TENDER",
                max_length=6,
                verbose_name="Type de besoin",
            ),
        ),
    ]
