# Generated by Django 4.2.2 on 2023-11-30 22:12

from django.db import migrations, models


def populate_tenders_sent_status(apps, schema_editor):
    Tender = apps.get_model("tenders", "Tender")

    for tender in Tender.objects.filter(validated_at__isnull=False):
        tender.sent_at = tender.validated_at
        tender.status = "SENT"
        tender.save()


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0062_tender_rename_kind_quote_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Brouillon"), ("PUBLISHED", "Publié"), ("VALIDATED", "Validé"), ("SENT", "Envoyé")],
                default="DRAFT",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
        migrations.RunPython(populate_tenders_sent_status),
    ]
