# Generated by Django 4.2.2 on 2023-11-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0062_tender_rename_kind_quote_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="location_distance",
            field=models.IntegerField(
                blank=True,
                help_text="Si vous décidez de faire un ciblage en km, vérifiez que le lieu d’intervention est bien renseigné et est une ville et que le kilométrage indiqué correspond à la réalité du besoin et des prestataires en face",  # noqa
                null=True,
                verbose_name="Distance en kilomètres autour du lieu d'intervention",
            ),
        ),
    ]
