# Generated by Django 4.2.2 on 2023-12-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0064_tender_status_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="limit_nb_siae_interested",
            field=models.PositiveSmallIntegerField(
                default=5, help_text="Champ renseigné par un ADMIN", verbose_name="Limite des SIAES intéressées"
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="limit_send_to_siae_batch",
            field=models.PositiveSmallIntegerField(
                default=10, help_text="Champ renseigné par un ADMIN", verbose_name="Nombre de SIAES par envoi"
            ),
        ),
    ]
