# Generated by Django 4.2.2 on 2023-12-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0064_tender_status_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="tendersiae",
            name="detail_cocontracting_click_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de clic sur Répondre en co-traitance"
            ),
        ),
    ]
