# Generated by Django 4.2.2 on 2023-12-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0065_tendersiae_detail_cocontracting_click_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="limit_nb_siae_interested",
            field=models.PositiveSmallIntegerField(
                default=5, help_text="Champ renseigné par un ADMIN", verbose_name="Limite des SIAES intéressées"
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="limit_send_to_siae_batch",
            field=models.PositiveSmallIntegerField(
                default=10, help_text="Champ renseigné par un ADMIN", verbose_name="Nombre de SIAES par envoi"
            ),
        ),
        migrations.RenameField(
            model_name="tender",
            old_name="sent_at",
            new_name="first_sent_at",
        ),
        migrations.AlterField(
            model_name="tender",
            name="first_sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date du premier envoi"),
        ),
        migrations.AddField(
            model_name="tender",
            name="last_sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date du dernier envoi"),
        ),
        migrations.AddField(
            model_name="tender",
            name="version",
            field=models.PositiveIntegerField(default=0, verbose_name="Version"),
        ),
        # this is migration to manage the existants stock
        migrations.AlterField(
            model_name="tender",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="Version"),
        ),
    ]
