# Generated by Django 4.2.9 on 2024-01-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0066_tender_limit_nb_siae_interested_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tendersiae",
            name="detail_not_interested_click_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de clic sur Pas intéressé"),
        ),
    ]
