# Generated by Django 4.2.9 on 2024-01-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0068_tender_siae_detail_cocontracting_and_not_interested_click_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="tendersiae",
            name="detail_not_interested_feedback",
            field=models.TextField(blank=True, verbose_name="Clic sur Pas intéréssé : explication"),
        ),
    ]
