# Generated by Django 4.2.9 on 2024-01-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0069_tendersiae_detail_not_interested_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="partner_approch_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="Partenaire APProch : ID"),
        ),
    ]
