# Generated by Django 4.2.2 on 2024-01-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0069_tendersiae_detail_not_interested_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="with_semantic_matching",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Effectue une recherche sémantique avec la description du besoin pour ajouter des structures au "
                    "ciblage traditionnel. La distance en kilomètres autour du lieu d'intervention (de type ville) "
                    "est prise en compte."
                ),
                verbose_name="Activer le ciblage alternatif IA",
            ),
        ),
        migrations.AddField(
            model_name="tendersiae",
            name="ai_had_found_it_too",
            field=models.BooleanField(default=False, verbose_name="Trouvé aussi par l'IA"),
        ),
        migrations.AlterField(
            model_name="tendersiae",
            name="source",
            field=models.CharField(
                choices=[("EMAIL", "E-mail"), ("DASHBOARD", "Dashboard"), ("LINK", "Lien"), ("AI", "IA")],
                default="EMAIL",
                max_length=20,
            ),
        ),
    ]
