# Generated by Django 4.2.9 on 2024-01-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0071_tender_partner_approch_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="contact_notification_disabled",
            field=models.BooleanField(
                default=False,
                help_text="Champ renseigné par un ADMIN",
                verbose_name="Le contact ne souhaite plus être contacté pour ce besoin",
            ),
        ),
    ]
