# Generated by Django 4.2.9 on 2024-02-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0072_tender_contact_notifications_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="tendersiae",
            name="survey_transactioned_amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Sondage transaction : montant du besoin"
            ),
        ),
        migrations.AddField(
            model_name="tendersiae",
            name="survey_transactioned_answer",
            field=models.BooleanField(blank=True, null=True, verbose_name="Sondage transaction : réponse"),
        ),
        migrations.AddField(
            model_name="tendersiae",
            name="survey_transactioned_answer_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Sondage transaction : date de réponse"),
        ),
        migrations.AddField(
            model_name="tendersiae",
            name="survey_transactioned_feedback",
            field=models.TextField(blank=True, verbose_name="Sondage transaction : retour d'expérience"),
        ),
        migrations.AddField(
            model_name="tendersiae",
            name="survey_transactioned_send_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Sondage transaction : date d'envoi de l'e-mail"
            ),
        ),
    ]
