# Generated by Django 4.2.2 on 2024-02-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0075_partnersharetender_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="constraints",
            field=models.TextField(blank=True, verbose_name="Comment répondre à cette demande ?"),
        ),
    ]
