# Generated by Django 4.2.9 on 2024-03-04 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenders", "0077_alter_tender_siae_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                help_text="Champ renseigné par un ADMIN",
                related_name="tenders_admins",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Admin(s) du besoin",
            ),
        ),
    ]
