# Generated by Django 4.2.9 on 2024-02-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0077_alter_tender_siae_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="tendersiae",
            name="is_deleted_by_siae",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Supprimé par l'utilisateur ?"),
        ),
    ]
