# Generated by Django 4.2.9 on 2024-03-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0079_tender_siae_transactioned_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="siae_transactioned_source",
            field=models.CharField(
                blank=True,
                choices=[("ADMIN", "Admin"), ("AUTHOR", "Auteur"), ("SIAE", "Structure")],
                help_text="Champ mis à jour automatiquement",
                max_length=20,
                null=True,
                verbose_name="Abouti à une transaction : source",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="siae_transactioned_last_updated",
            field=models.DateTimeField(
                blank=True,
                help_text="Champ mis à jour automatiquement",
                null=True,
                verbose_name="Abouti à une transaction : date de mise à jour",
            ),
        ),
    ]
