# Generated by Django 4.2.9 on 2024-03-13 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0078_tendersiae_is_deleted_by_siae"),
        ("tenders", "0080_tender_siae_transactioned_source_and_more"),
    ]

    operations = []
