# Generated by Django 4.2.9 on 2024-03-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0081_merge_20240313_1141"),
    ]

    operations = [
        migrations.AddField(
            model_name="tendersiae",
            name="transactioned",
            field=models.BooleanField(
                blank=True,
                help_text="Champ renseigné par un ADMIN",
                null=True,
                verbose_name="Abouti à une transaction avec l'acheteur",
            ),
        ),
        migrations.AddField(
            model_name="tendersiae",
            name="transactioned_source",
            field=models.CharField(
                blank=True,
                choices=[("ADMIN", "Admin"), ("AUTHOR", "Auteur"), ("SIAE", "Structure")],
                help_text="Champ mis à jour automatiquement",
                max_length=20,
                null=True,
                verbose_name="Abouti à une transaction avec l'acheteur : source",
            ),
        ),
    ]
