# Generated by Django 4.2.9 on 2024-04-08 08:12

from django.db import migrations, models


def transform_boolean_to_char(apps, schema_editor):
    Tender = apps.get_model("tenders", "Tender")
    for obj in Tender.objects.all():
        if obj.survey_transactioned_answer in [True, "true"]:
            obj.survey_transactioned_answer = "1"
        elif obj.survey_transactioned_answer in [False, "false"]:
            obj.survey_transactioned_answer = "0"
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0083_tendersiae_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="survey_transactioned_answer",
            field=models.CharField(
                blank=True,
                choices=[("0", "Non"), ("1", "Oui"), ("?", "Pas encore")],
                null=True,
                verbose_name="Sondage transaction : réponse",
            ),
        ),
        migrations.RunPython(transform_boolean_to_char),
    ]
