# Generated by Django 4.2.9 on 2024-04-17 08:44

from django.db import migrations, models

import lemarche.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0084_alter_tender_survey_transactioned_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="external_link",
            field=models.CharField(
                blank=True,
                help_text="Ajoutez ici l'URL de votre appel d'offres",
                validators=[lemarche.utils.validators.OptionalSchemeURLValidator()],
                verbose_name="Lien vers l'appel d'offres",
            ),
        ),
        migrations.AlterField(
            model_name="tendersiae",
            name="source",
            field=models.CharField(
                choices=[("EMAIL", "E-mail"), ("DASHBOARD", "Dashboard"), ("LINK", "Lien"), ("AI", "IA")],
                default="EMAIL",
                max_length=20,
                verbose_name="Source de la mise en relation",
            ),
        ),
    ]
