# Generated by Django 4.2.9 on 2024-04-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0085_alter_tender_external_link_alter_tendersiae_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="limit_nb_siae_interested",
            field=models.PositiveSmallIntegerField(
                default=6, help_text="Champ renseigné par un ADMIN", verbose_name="Limite des SIAES intéressées"
            ),
        ),
    ]
