# Generated by Django 4.2.9 on 2024-05-02 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0086_alter_tender_limit_nb_siae_interested"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="crm_id",
            field=models.CharField(
                blank=True,
                max_length=80,
                null=True,
                validators=[django.core.validators.MinLengthValidator(8)],
                verbose_name="Brevo crm id",
            ),
        ),
    ]
