# Generated by Django 4.2.13 on 2024-05-17 13:34

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0087_tender_brevo_deal_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="contact_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Renseignez votre numéro de téléphone professionnel",
                max_length=20,
                region=None,
                verbose_name="Téléphone du contact",
            ),
        ),
    ]
