# Generated by Django 4.2.13 on 2024-06-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0088_alter_tender_contact_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="le_marche_doesnt_exist_how_to_find_siae",
            field=models.CharField(
                choices=[
                    ("DK", "Je ne sais pas"),
                    ("IS", "Recherche sur Internet (Google, page jaune, recherche sur le web)"),
                    ("NW", "Réseaux professionnels et partenariats"),
                    ("DI", "Annuaire spécialisé (GESAT, UNEA, Handeco)"),
                    (
                        "RC",
                        (
                            "Recommandations et bouche-à-oreille (Réseaux sociaux, "
                            "recommandations personnelles, collègues)"
                        ),
                    ),
                    ("KP", "Prestataires connus et habituels (Fournisseurs actuels)"),
                    ("PT", "Appel d'offres et consultations publiques (BOAMP, JOUE, AWS, appels d'offres)"),
                    ("FA", "Facilitateurs de clauses sociales"),
                    (
                        "LS",
                        (
                            "Sourcing local et salons professionnels (Recherche locale, "
                            "salons, événements professionnels)"
                        ),
                    ),
                ],
                default="DK",
                help_text="Comment auriez-vous fait pour consulter des prestataires inclusifs ?",
                max_length=2,
                verbose_name="Sans le marché de l'inclusion",
            ),
        ),
    ]
