# Generated by Django 4.2.13 on 2024-06-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0088_alter_tender_contact_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="le_marche_doesnt_exist_how_to_find_siae",
            field=models.CharField(
                choices=[
                    ("i-dont-know", "Je ne sais pas"),
                    ("internet-search", "Recherche sur Internet (Google, page jaune, recherche sur le web)"),
                    ("networks", "Réseaux professionnels et partenariats"),
                    ("directory", "Annuaire spécialisé (GESAT, UNEA, Handeco)"),
                    (
                        "recommendations",
                        (
                            "Recommandations et bouche-à-oreille (Réseaux sociaux, recommandations personnelles,"
                            " collègues)"
                        ),
                    ),
                    ("known-providers", "Prestataires connus et habituels (Fournisseurs actuels)"),
                    (
                        "public-tenders",
                        "Appel d'offres et consultations publiques (BOAMP, JOUE, AWS, appels d'offres)",
                    ),
                    ("facilitators", "Facilitateurs de clauses sociales"),
                    (
                        "local-sourcing",
                        (
                            "Sourcing local et salons professionnels (Recherche locale, salons, événements"
                            " professionnels)"
                        ),
                    ),
                ],
                default="i-dont-know",
                help_text="Comment auriez-vous fait pour consulter des prestataires inclusifs ?",
                max_length=15,
                verbose_name="Sans le marché de l'inclusion",
            ),
        ),
    ]
