# Generated by Django 4.2.13 on 2024-07-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0090_tender_remove_hubspot_deal_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="is_followed_by_us",
            field=models.BooleanField(null=True, verbose_name="Suivi par l'équipe"),
        ),
        migrations.AddField(
            model_name="tender",
            name="is_reserved_tender",
            field=models.BooleanField(null=True, verbose_name="Appel d'offre reservé"),
        ),
        migrations.AddField(
            model_name="tender",
            name="proj_link_to_tender",
            field=models.URLField(
                blank=True,
                help_text="Doit commencer par http:// ou https://",
                verbose_name="Lien vers l'appel d'offre",
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="proj_resulted_in_reserved_tender",
            field=models.BooleanField(null=True, verbose_name="Abouti à un appel d’offre (uniquement sourcing)"),
        ),
    ]
