# Generated by Django 4.2.15 on 2024-10-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0092_tender_send_to_commercial_partners_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="send_to_commercial_partners_only",
            field=models.BooleanField(default=False, verbose_name="Envoyer uniquement aux partenaires commerciaux"),
        ),
    ]
