# Generated by Django 4.2.15 on 2025-01-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0094_add_templatetransactional_tender_author_commercial_partners"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tender",
            name="accept_cocontracting",
        ),
        migrations.RemoveField(
            model_name="tender",
            name="siae_detail_cocontracting_click_count",
        ),
        migrations.RemoveField(
            model_name="tendersiae",
            name="detail_cocontracting_click_date",
        ),
        migrations.AddField(
            model_name="tender",
            name="_accept_cocontracting",
            field=models.BooleanField(default=False, verbose_name="Archivé"),
        ),
        migrations.AddField(
            model_name="tender",
            name="_siae_detail_cocontracting_click_count",
            field=models.IntegerField(default=0, verbose_name="Archivé"),
        ),
        migrations.AddField(
            model_name="tendersiae",
            name="_detail_cocontracting_click_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Archivé"),
        ),
    ]
