# Generated by Django 4.2.15 on 2024-11-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0094_add_templatetransactional_tender_author_commercial_partners"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="email_sent_for_modification",
            field=models.BooleanField(default=False, help_text="E-mail envoyé pour modification"),
        ),
    ]
