# Generated by Django 4.2.15 on 2024-11-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0095_tender_email_sent_for_modification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="email_sent_for_modification",
            field=models.BooleanField(default=False, verbose_name="Besoin non valide"),
        ),
    ]
