# Generated by Django 4.2.15 on 2024-11-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0096_alter_tender_email_sent_for_modification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tender",
            name="email_sent_for_modification",
        ),
        migrations.AddField(
            model_name="tender",
            name="is_data_valid",
            field=models.BooleanField(null=True, verbose_name="Besoin valide"),
        ),
    ]
