# Generated by Django 5.1.6 on 2025-04-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0097_questionanswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="external_link",
            field=models.URLField(
                blank=True,
                help_text="Ajoutez ici l'URL de votre appel d'offres",
                verbose_name="Lien vers l'appel d'offres",
            ),
        ),
    ]
