# Generated by Django 4.2.15 on 2024-11-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0097_remove_tender_email_sent_for_modification_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tender",
            name="is_data_valid",
        ),
        migrations.AddField(
            model_name="tender",
            name="email_sent_for_modification",
            field=models.BooleanField(default=False, verbose_name="Modifications requises"),
        ),
    ]
