# Generated by Django 5.1.6 on 2025-04-17 15:50

from django.db import migrations, models


def update_submitted_tenders(apps, schema_editor):
    """
    Update status field value for SUBMITTED tenders
    """
    Tender = apps.get_model("tenders", "Tender")
    Tender.objects.filter(status="PUBLISHED").update(status="SUBMITTED")


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0098_update_rejected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("SUBMITTED", "Déposé"),
                    ("VALIDATED", "Validé"),
                    ("SENT", "Envoyé"),
                    ("REJECTED", "Rejeté"),
                ],
                default="DRAFT",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
        migrations.RunPython(update_submitted_tenders, migrations.RunPython.noop),
    ]
