# Generated by Django 5.1.6 on 2025-04-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0098_update_rejected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("SUBMITTED", "Déposé"),
                    ("VALIDATED", "Validé"),
                    ("SENT", "Envoyé"),
                    ("REJECTED", "Rejeté"),
                ],
                default="DRAFT",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
    ]
