# Generated by Django 5.1.6 on 2025-02-27 21:28

from django.db import migrations, models

import lemarche.tenders.models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0099_alter_tender_external_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="attachment_one",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=lemarche.tenders.models.tender_attachment_directory_path,
                verbose_name="Premier fichier joint",
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="attachment_three",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=lemarche.tenders.models.tender_attachment_directory_path,
                verbose_name="Troisième fichier joint",
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="attachment_two",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=lemarche.tenders.models.tender_attachment_directory_path,
                verbose_name="Deuxième fichier joint",
            ),
        ),
    ]
