# Generated by Django 5.1.6 on 2025-05-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0100_tender_attachment_one_tender_attachment_three_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tender",
            name="marche_benefits",
        ),
    ]
