# Generated by Django 5.1.6 on 2025-05-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0102_alter_tender_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuggestedQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(verbose_name="Texte de la question")),
            ],
            options={
                "verbose_name": "Question suggérée",
                "verbose_name_plural": "Questions suggérées",
            },
        ),
    ]
