# Generated by Django 5.1.6 on 2025-06-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0103_suggestedquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="constraints_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Titre des contraintes"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="source",
            field=models.CharField(
                choices=[
                    ("FORM", "Formulaire"),
                    ("STAFF_C4_CREATED", "Staff Marché (via l'Admin)"),
                    ("API", "API"),
                    ("TALLY", "TALLY"),
                ],
                default="FORM",
                max_length=20,
                verbose_name="Source",
            ),
        ),
        migrations.CreateModel(
            name="TenderInstruction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120, verbose_name="Titre")),
                ("text", models.TextField(verbose_name="Contenu")),
                (
                    "tender_type",
                    models.CharField(
                        choices=[("TENDER", "Appel d'offres"), ("QUOTE", "Demande de devis"), ("PROJ", "Sourcing")],
                        max_length=10,
                    ),
                ),
                (
                    "tender_source",
                    models.CharField(
                        choices=[
                            ("FORM", "Formulaire"),
                            ("STAFF_C4_CREATED", "Staff Marché (via l'Admin)"),
                            ("API", "API"),
                            ("TALLY", "TALLY"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notice de réponse au besoin d'achat",
                "verbose_name_plural": "Notices de réponse au besoin d'achat",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tender_type", "tender_source"),
                        name="unique_instruction_for_each_tender_type_and_source",
                    )
                ],
            },
        ),
    ]
