# Generated by Django 5.1.6 on 2025-08-19 12:18

import uuid

from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    """Even if we have passed a callable to the default value, it's called only once, hence all the rows
    share the same uuid.
    Here we generate a new uuid for each row.
    """
    TenderSiae = apps.get_model("tenders", "TenderSiae")
    for row in TenderSiae.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0104_tender_constraints_title_alter_tender_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tendersiae",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(gen_uuid, migrations.RunPython.noop),
    ]
