# Generated by Django 5.1.6 on 2025-09-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0105_tendersiae_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="reminder_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tender",
            name="reminder_last_update",
            field=models.DateTimeField(null=True),
        ),
    ]
