# Generated by Django 4.2.2 on 2023-07-13 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0050_alter_tender_source"),
        ("notes", "0002_note_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="tender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="tenders.tender",
                verbose_name="Besoin d'achat",
            ),
        ),
    ]
