# Generated by Django 5.2.11 on 2026-03-05 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_anonymized",
        ),
    ]
