# Generated by Django 5.2.11 on 2026-03-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_is_anonymized"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pending_deletion_notice_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de notification de suppression de l'utilisateur"
            ),
        ),
    ]
