# Generated by Django 3.2.7 on 2021-09-15 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='c1_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='user',
            name='kind',
            field=models.CharField(choices=[('PERSO', 'Une personne'), ('COMPANY', 'Une entreprise'), ('BUYER', 'Un acheteur qui souhaite réaliser un achat inclusif'), ('SIAE', 'Structure inclusive qui souhaite proposer ses offres'), ('ADMIN', 'Administrateur.trice'), ('PARTNER', 'Partenaire')], default='PERSO', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='user',
            name='siret',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Siret ou Siren'),
        ),
        migrations.AddField(
            model_name='user',
            name='naf',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Naf'),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Clé API'),
        ),
    ]
