# Generated by Django 3.2.7 on 2021-09-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_update_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kind',
            field=models.CharField(choices=[('SIAE', 'SIAE'), ('BUYER', 'Acheteur (classique)'), ('PARTNER', 'Partenaire'), ('ADMIN', 'Administrateur')], max_length=20, verbose_name='Type'),
        ),
    ]
