# Generated by Django 3.2.7 on 2021-10-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20210930_2317"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SIAE", "Structure"),
                    ("BUYER", "Acheteur"),
                    ("PARTNER", "Partenaire"),
                    ("ADMIN", "Administrateur"),
                ],
                max_length=20,
                null=True,
                verbose_name="Type",
            ),
        ),
    ]
