# Generated by Django 3.2.8 on 2021-10-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_kind"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="c4_company_name",
            new_name="company_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="c4_offers_for_pro_sector",
            new_name="accept_offers_for_pro_sector",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="c4_quote_promise",
            new_name="accept_quote_promise",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="c4_accept_rgpd",
            new_name="accept_rgpd",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="c4_accept_survey",
            new_name="accept_survey",
        ),
    ]
