# Generated by Django 3.2.8 on 2021-10-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_kind"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="c4_company_name",
            new_name="company_name",
        ),
    ]
