# Generated by Django 3.2.8 on 2021-10-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_rename_c4_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image_name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de l'image"),
        ),
        migrations.AddField(
            model_name="user",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="Lien vers l'image"),
        ),
    ]
