# Generated by Django 3.2.8 on 2021-11-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_avoid_null_on_charfields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="partner_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FACILITATEUR", "Facilitateur des clauses sociales"),
                    ("RESEAU_IAE", "Réseaux IAE"),
                    ("RESEAU_HANDICAP", "Réseau secteur Handicap"),
                    ("DREETS", "DREETS / DDETS"),
                    ("PRESCRIPTEUR", "Prescripteur"),
                    ("PUBLIC", "Organisme public"),
                    ("PRIVE", "Organisme privé"),
                    ("AUTRE", "Autre"),
                ],
                max_length=20,
                verbose_name="Type de partenaire",
            ),
        ),
    ]
