# Generated by Django 4.0.2 on 2022-04-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_user_api_key_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accept_share_contact_to_external_partners",
            field=models.BooleanField(
                default=False,
                help_text="J'accepte que mes coordonnées de contact soient partagées avec les partenaires externes du Marché de l'inclusion afin de recevoir des opportunités commerciales (appels d'offres, marché ...)",  # noqa
                verbose_name="Partage de contact à des partenaires externes",
            ),
        ),
    ]
