# Generated by Django 4.0.6 on 2022-08-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_user_accept_share_contact_to_external_partners"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dashboard_last_seen_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de dernière visite sur la page 'tableau de bord'"
            ),
        ),
    ]
