# Generated by Django 4.0.6 on 2022-08-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_user_dashboard_last_seen_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tender_list_last_seen_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de dernière visite sur la page 'besoins'"
            ),
        ),
    ]
