# Generated by Django 4.1.2 on 2022-10-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_user_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="extra_data",
            field=models.JSONField(default=dict, editable=False, verbose_name="Données complémentaires"),
        ),
    ]
