# Generated by Django 4.1.2 on 2022-10-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_user_extra_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_display_tender_contact_details",
            field=models.BooleanField(
                default=False,
                help_text="Permet à certains utilisateurs partenaires de voir directement les coordonnées. Les autres auront un message leur demandant de contacter les admins",  # noqa
                verbose_name="Ce partenaire a accès aux coordonnées de l'acheteur ?",
            ),
        ),
    ]
