# Generated by Django 4.1.3 on 2022-12-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_user_can_display_tender_contact_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="buyer_kind",
            field=models.CharField(
                blank=True,
                choices=[("PUBLIC", "Public"), ("PRIVE", "Privé")],
                max_length=20,
                verbose_name="Type d'acheteur",
            ),
        ),
    ]
