# Generated by Django 4.1.3 on 2022-12-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_user_buyer_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="buyer_kind_detail",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PUBLIC_MINISTRY", "Public : Ministère"),
                    ("PUBLIC_ESTABLISHMENT", "Public : Établissement public"),
                    ("PUBLIC_COLLECTIVITY", "Public : Collectivité"),
                    ("PUBLIC_ASSOCIATION", "Public : Association"),
                    ("PRIVATE_BIG_CORP", "Privé : Grand groupe"),
                    ("PRIVATE_ETI", "Privé : ETI"),
                    ("PRIVATE_PME", "Privé : PME"),
                    ("PRIVATE_TPE", "Privé : TPE"),
                ],
                max_length=20,
                verbose_name="Type d'acheteur (détail)",
            ),
        ),
    ]
