# Generated by Django 4.1.3 on 2023-01-23 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0004_alter_network_slug"),
        ("users", "0023_user_buyer_kind_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="partner_network",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_partners",
                to="networks.network",
                verbose_name="Réseau du partenaire",
            ),
        ),
    ]
