# Generated by Django 4.1.9 on 2023-07-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_user_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="source",
            field=models.CharField(
                choices=[
                    ("SIGNUP_FORM", "Formulaire d'inscription"),
                    ("TALLY_FORM", "Formulaire verticale"),
                    ("TENDER_FORM", "Formulaire de dépôt de besoin"),
                    ("DJANGO_ADMIN", "Admin Django"),
                ],
                default="SIGNUP_FORM",
                max_length=20,
            ),
        ),
    ]
