# Generated by Django 4.2.2 on 2023-08-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_alter_user_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_list_count",
            field=models.IntegerField(default=0, verbose_name="Nombre de listes de favoris"),
        ),
    ]
