# Generated by Django 4.2.2 on 2023-08-22 14:31

from django.db import migrations


def populate_favorite_list_count(apps, schema_editor):
    User = apps.get_model("users", "User")
    # for user in User.objects.prefetch_related("favorite_lists").has_favorite_list():
    for user in User.objects.all():
        user.favorite_list_count = user.favorite_lists.count()
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_user_favorite_list_count"),
    ]

    operations = [
        migrations.RunPython(populate_favorite_list_count),
    ]
