# Generated by Django 4.2.5 on 2023-11-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sectors", "0003_sector_sectorgroup_ordering"),
        ("users", "0029_user_populate_favorite_list_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sectors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Quelles sont les familles d’achat sur lesquelles vous travaillez ?",
                related_name="users",
                to="sectors.sector",
                verbose_name="Secteurs d'activité",
            ),
        ),
    ]
