# Generated by Django 4.2.2 on 2023-11-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0030_user_sectors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="buyer_kind_detail",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRIVATE_BIG_CORP", "Grand groupe (+5000 salariés)"),
                    ("PRIVATE_ETI", "ETI (+250 salariés)"),
                    ("PRIVATE_PME", "PME (+10 salariés)"),
                    ("PRIVATE_TPE", "TPE"),
                    ("PUBLIC_ASSOCIATION", "Association"),
                    ("PUBLIC_COLLECTIVITY", "Collectivité"),
                    ("PUBLIC_ESTABLISHMENT", "Établissement public"),
                    ("PUBLIC_MINISTRY", "Ministère"),
                ],
                max_length=20,
                verbose_name="Type d'acheteur (détail)",
            ),
        ),
    ]
