# Generated by Django 4.2.2 on 2023-12-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0031_user_rename_buyer_kind_detail_display"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SIAE", "Structure"),
                    ("BUYER", "Acheteur"),
                    ("PARTNER", "Partenaire"),
                    ("INDIVIDUAL", "Particulier"),
                    ("ADMIN", "Administrateur"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
