# Generated by Django 4.2.9 on 2024-05-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0032_alter_user_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="brevo_contact_id",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Brevo contact id"),
        ),
    ]
