# Generated by Django 4.2.13 on 2024-06-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0034_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="accept_rgpd",
            field=models.BooleanField(default=False),
        ),
    ]
