# Generated by Django 4.2.13 on 2024-06-19 15:49

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0035_alter_user_accept_rgpd"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="user_email_ci_uniqueness",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Cette adresse e-mail est déjà utilisée."},
                max_length=254,
                unique=True,
                verbose_name="Adresse e-mail",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="user_email_ci_uniqueness",
                violation_error_message="",
            ),
        ),
    ]
