# Generated by Django 4.2.13 on 2024-06-26 13:00

from django.db import migrations


def remove_hubspot_contact_id(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        if "hubspot_contact_id" in user.extra_data:
            del user.extra_data["hubspot_contact_id"]
            user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0037_rename_extra_data_last_year_key"),
    ]

    operations = [
        migrations.RunPython(remove_hubspot_contact_id, migrations.RunPython.noop),
    ]
