# Generated by Django 4.2.13 on 2024-09-12 15:33

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0038_user_remove_hubspot_contact_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="user_email_ci_uniqueness",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="user_email_ci_uniqueness",
                violation_error_message="Cette adresse e-mail est déjà utilisée.",
            ),
        ),
    ]
