# Generated by Django 4.2.15 on 2024-12-23 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0039_remove_user_user_email_ci_uniqueness_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="c4_email_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="c4_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="c4_id_card_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="c4_naf",
        ),
        migrations.RemoveField(
            model_name="user",
            name="c4_phone_prefix",
        ),
        migrations.RemoveField(
            model_name="user",
            name="c4_phone_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="c4_siret",
        ),
        migrations.RemoveField(
            model_name="user",
            name="c4_time_zone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="c4_website",
        ),
    ]
