# Generated by Django 4.2.15 on 2024-11-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0039_remove_user_user_email_ci_uniqueness_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="old_api_keys",
            field=models.JSONField(blank=True, default=list, verbose_name="Anciennes clés API"),
        ),
    ]
