# Generated by Django 4.2.15 on 2024-12-24 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0040_remove_user_c4_email_verified_remove_user_c4_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="image_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="image_url",
        ),
    ]
