# Generated by Django 4.2.15 on 2024-10-29 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0043_user_is_anonymized"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="api_key",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(64)],
                verbose_name="Clé API",
            ),
        ),
    ]
