# Generated by Django 4.2.15 on 2024-12-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0043_update_inactive_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_anonymized",
            field=models.BooleanField(default=False, verbose_name="L'utilisateur à été anonymisé"),
        ),
    ]
