# Generated by Django 5.1.6 on 2025-02-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0044_alter_user_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_onboarded",
            field=models.BooleanField(default=True, verbose_name="L'utilisateur à suivi la prodédure d'onboarding"),
        ),
    ]
