# Generated by Django 5.1.6 on 2025-06-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0045_user_is_onboarded"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_onboarded",
            new_name="have_followed_onboarding",
        ),
        migrations.AlterField(
            model_name="user",
            name="have_followed_onboarding",
            field=models.BooleanField(default=False, verbose_name="L'utilisateur a suivi la procédure d'onboarding"),
        ),
    ]
