# Generated by Django 5.1.6 on 2025-06-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0045_user_is_onboarded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_onboarded",
            field=models.BooleanField(default=False, verbose_name="L'utilisateur a suivi la procédure d'onboarding"),
        ),
    ]
