# Generated by Django 4.2.13 on 2024-06-23 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Datum",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.TextField()),
                ("bucket", models.TextField(verbose_name="Unique value for the code (for example the date of today)")),
                ("value", models.IntegerField()),
                ("measured_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "data",
                "indexes": [models.Index(fields=["measured_at", "code"], name="analytics_d_measure_a59c08_idx")],
                "unique_together": {("code", "bucket")},
            },
        ),
    ]
