# Generated by Django 4.2.13 on 2024-06-05 13:05

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Datum",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("code", models.TextField(choices=[("SIAE-001", "SIAE completion")])),
                ("bucket", models.TextField()),
                ("value", models.IntegerField()),
                ("measured_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "data",
                "indexes": [models.Index(fields=["measured_at", "code"], name="analytics_d_measure_a59c08_idx")],
                "unique_together": {("code", "bucket")},
            },
        ),
    ]
