# Generated by Django 3.2.7 on 2021-09-14 15:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.flatpage')),
                ('meta_title', models.CharField(blank=True, default='', help_text='Le titre qui sera affiché dans les SERPs. Il est recommandé de le garder < 60 caractères. Laissez vide pour réutiliser le titre de la page.', max_length=100, verbose_name='Titre (balise meta)')),
                ('meta_description', models.TextField(blank=True, default='', help_text='La description qui sera affichée dans les SERPs. À garder < 150 caractères.', max_length=255, verbose_name='Description (balise meta)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            bases=('flatpages.flatpage',),
        ),
    ]
