# Generated by Django 4.1.3 on 2023-01-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_full_page",
            field=models.BooleanField(
                default=True,
                help_text="Décocher si vous souhaitez intégrer ce contenu dans une page existante.",
                verbose_name="Page entière ?",
            ),
        ),
    ]
