# Generated by Django 4.2.15 on 2024-11-19 17:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_pagefragment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="flatpage_ptr",
        ),
        migrations.DeleteModel(
            name="PageFragment",
        ),
        migrations.DeleteModel(
            name="Page",
        ),
    ]
