#!/bin/sh
export MYSQL_HOST=${MYSQL_ADDON_HOST}
export MYSQL_DB=${MYSQL_ADDON_DB}
export MYSQL_PORT=${MYSQL_ADDON_PORT}
export MYSQL_PASSWORD=${MYSQL_ADDON_PASSWORD}
export MYSQL_USER=${MYSQL_ADDON_USER}
