# Generated by Django 5.1.6 on 2025-02-11 08:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGuide",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="Nom du Guide")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date de modification")),
                (
                    "guided_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Utilisateurs qui ont déjà été guidés",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateurs guidés",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL de la page à guider", max_length=250, unique=True, verbose_name="URL"
                    ),
                ),
                (
                    "url_path",
                    models.CharField(
                        help_text="C'est l'identifiant unique de l'url",
                        max_length=250,
                        unique=True,
                        verbose_name="chemin URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guide utilisateurs",
                "verbose_name_plural": "Guides utilisateurs",
            },
        ),
        migrations.CreateModel(
            name="GuideStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Titre dans la popup")),
                ("text", models.TextField(blank=True, verbose_name="Contenu text de l'étape")),
                ("element", models.CharField(max_length=200, verbose_name="Élément css à rattacher")),
                (
                    "position",
                    models.CharField(
                        choices=[("top", "Top"), ("bottom", "Bottom"), ("left", "Left"), ("right", "Right")],
                        max_length=50,
                    ),
                ),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="django_shepherd.userguide",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étape du guide",
                "verbose_name_plural": "Étapes du guide",
            },
        ),
    ]
