# Generated by Django 4.2.13 on 2024-06-28 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_shepherd", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userguide",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
        ),
        migrations.AddField(
            model_name="userguide",
            name="slug",
            field=models.SlugField(
                help_text="Identifiant permettant d'identifier le guide en js",
                null=True,
                unique=True,
                verbose_name="Slug (unique)",
            ),
        ),
        migrations.AddField(
            model_name="userguide",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Date de modification"),
        ),
        migrations.AlterField(
            model_name="guidestep",
            name="element",
            field=models.CharField(max_length=200, null=True, verbose_name="Élément css à rattacher"),
        ),
        migrations.AlterField(
            model_name="guidestep",
            name="position",
            field=models.CharField(
                choices=[("top", "Top"), ("bottom", "Bottom"), ("left", "Left"), ("right", "Right")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="guidestep",
            name="text",
            field=models.TextField(verbose_name="Contenu text de l'étape"),
        ),
        migrations.AlterField(
            model_name="guidestep",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Titre dans la popup"),
        ),
        migrations.AlterField(
            model_name="userguide",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="userguide",
            name="name",
            field=models.CharField(max_length=200, unique=True, verbose_name="Nom du Guide"),
        ),
    ]
