# Generated by Django 4.2.17 on 2025-02-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_shepherd", "0002_userguide_created_at_userguide_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guidestep",
            options={"verbose_name": "Étape du guide", "verbose_name_plural": "Étapes du guide"},
        ),
        migrations.AlterModelOptions(
            name="userguide",
            options={"verbose_name": "Guide utilisateurs", "verbose_name_plural": "Guides utilisateurs"},
        ),
        migrations.AlterField(
            model_name="guidestep",
            name="element",
            field=models.CharField(max_length=200, verbose_name="Élément css à rattacher"),
        ),
        migrations.AlterField(
            model_name="guidestep",
            name="position",
            field=models.CharField(
                choices=[("TOP", "Top"), ("BOTTOM", "Bottom"), ("LEFT", "Left"), ("RIGHT", "Right")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="userguide",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="userguide",
            name="slug",
            field=models.SlugField(
                help_text="Identifiant permettant d'identifier le guide en js",
                unique=True,
                verbose_name="Slug (unique)",
            ),
        ),
    ]
