# Generated by Django 4.2.17 on 2025-02-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_shepherd", "0003_alter_guidestep_options_alter_userguide_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidestep",
            name="position",
            field=models.CharField(
                choices=[("top", "Top"), ("bottom", "Bottom"), ("left", "Left"), ("right", "Right")], max_length=50
            ),
        ),
    ]
