# Generated by Django 4.2.17 on 2025-02-03 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_shepherd", "0004_alter_guidestep_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="userguide",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
