# Generated by Django 4.2.17 on 2025-02-03 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_shepherd", "0005_userguide_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userguide",
            name="users",
        ),
        migrations.AddField(
            model_name="userguide",
            name="guided_users",
            field=models.ManyToManyField(
                help_text="Utilisateurs qui ont déjà été guidés",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateurs guidés",
            ),
        ),
    ]
