# Generated by Django 4.2.17 on 2025-02-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_shepherd", "0006_remove_userguide_users_userguide_guided_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="userguide",
            name="url",
            field=models.URLField(
                default="http:/:google.com",
                help_text="URL de la page à guider",
                max_length=250,
                unique=True,
                verbose_name="URL",
            ),
            preserve_default=False,
        ),
    ]
