# Generated by Django 5.1.6 on 2025-05-05 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sectors", "0003_sector_sectorgroup_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sector",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sectors",
                to="sectors.sectorgroup",
                verbose_name="Groupe parent",
            ),
        ),
    ]
