# Generated by Django 3.2.4 on 2021-06-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c4_directory', '0004_alter_siae_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='siae',
            name='sectors',
            field=models.ManyToManyField(to='c4_directory.Sector'),
        ),
    ]
