# Generated by Django 5.1.11 on 2025-10-09 10:40

import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleList",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Titre de l'encart")),
                ("slug", models.SlugField(help_text="Identifiant", max_length=255, unique=True, verbose_name="slug")),
                ("content", wagtail.fields.RichTextField(blank=True, verbose_name="Contenu")),
            ],
            options={
                "verbose_name": "Paragraphe",
                "verbose_name_plural": "Paragraphes",
            },
        ),
    ]
