# Generated by Django 5.1.11 on 2025-10-09 12:01

from django.db import migrations


def add_paragraph(apps, schema_editor):
    Paragraph = apps.get_model("cms", "Paragraph")
    Paragraph.objects.create(
        title="Prise de rendez vous",
        slug="rdv-signup",
        content='<h2 data-block-key="bafwd">Bienvenue !</h2><p data-block-key="qrk4">Prenez RDV avec nos experts pour activer votre compte et accéder à '  # noqa
        'l\'ensemble des fonctionnalités du Marché de l\'inclusion</p><p data-block-key="c66kr"><b>✓ 2500 fournisseurs labélisés Handicap (EA &amp; ESAT)</b></p><p data-block-key="f4v3j">'  # noqa
        '<b>✓ 4000 fournisseurs labélisés insertion par l\'activité économiques (IAE)</b></p><p data-block-key="bicu4"><b>✓ Réduisez le temps consacré à vos sourcing achat inclusif</b></p>',  # noqa
    )
    Paragraph.objects.create(
        title="Vous avez des question ?",
        slug="rdv-contact",
        content='<h4 data-block-key="2tu4c"><b>Vous avez des questions ?</b></h4><p data-block-key="3vo75">Contactez nous au<br/><b>06 66 66 66 66</b></p>',  # noqa
    )


class Migration(migrations.Migration):
    replaces = [("cms", "0015_paragraph")]

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_paragraph, migrations.RunPython.noop),
    ]
