# Generated by Django 4.1.6 on 2023-03-10 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("cms", "0002_articlepage_with_cta_tender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Titre de l'encart")),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "id_call_to_action",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="id du call to action (pour le suivi)",
                        max_length=255,
                        verbose_name="slug",
                    ),
                ),
                ("call_to_action", models.CharField(max_length=255, verbose_name="Titre du call to action")),
                (
                    "open_in_new_tab",
                    models.BooleanField(blank=True, default=True, verbose_name="Ouvrir dans une nouvelle fenêtre"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Panneau publicitaire",
            },
        ),
    ]
