# Generated by Django 4.1.6 on 2023-03-28 11:51

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_homepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("website_stats", wagtail.blocks.StructBlock([])),
                    (
                        "section_they_publish_tenders",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        default="Ils ont publié un besoin sur le marché", max_length=120, required=True
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "section_studies_cases_tenders",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        default="100% des besoins ont reçu des réponses en 24h",
                                        max_length=120,
                                        required=True,
                                    ),
                                ),
                                (
                                    "subtitle",
                                    wagtail.blocks.CharBlock(
                                        default="Gagnez du temps en utilisant le marché.",
                                        max_length=120,
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "section_our_siaes",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "subtitle",
                                    wagtail.blocks.RichTextBlock(
                                        default="\n            Faire appel à nos 8500 prestataires inclusifs, c'est la garantie d'être accompagné\n            par des professionnels reconnus et certifiés dans leur domaine.\n        ",  # noqa
                                        features=["bold", "italic"],
                                        required=True,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "section_our_ressources",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(default="Nos ressources", max_length=120, required=True),
                                )
                            ]
                        ),
                    ),
                    (
                        "section_what_find_here",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(default="Sur le marché", max_length=120, required=True),
                                )
                            ]
                        ),
                    ),
                    (
                        "section_our_partners",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        default="Les partenaires du marché", max_length=120, required=True
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
    ]
