# Generated by Django 4.1.6 on 2023-04-27 13:27

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0006_alter_homepage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("website_stats", wagtail.blocks.StructBlock([])),
                    (
                        "section_they_publish_tenders",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        default="Ils ont publié un besoin sur le marché", max_length=120, required=True
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "section_studies_cases_tenders",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        default="100% des besoins ont reçu des réponses en 24h",
                                        max_length=120,
                                        required=True,
                                    ),
                                ),
                                (
                                    "subtitle",
                                    wagtail.blocks.CharBlock(
                                        default="Gagnez du temps en utilisant le marché.",
                                        max_length=120,
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "section_our_siaes",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        default="Les prestataires inclusifs, des partenaires d'excellence",
                                        max_length=60,
                                        required=True,
                                    ),
                                ),
                                (
                                    "subtitle",
                                    wagtail.blocks.RichTextBlock(
                                        default="\n            Faire appel à nos 8500 prestataires inclusifs, c'est la garantie d'être accompagné\n            par des professionnels reconnus et certifiés dans leur domaine.\n        ",  # noqa
                                        features=["bold", "italic"],
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "section_our_ressources",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(default="Nos ressources", max_length=120, required=True),
                                )
                            ]
                        ),
                    ),
                    (
                        "section_what_find_here",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(default="Sur le marché", max_length=120, required=True),
                                )
                            ]
                        ),
                    ),
                    (
                        "section_our_partners",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        default="Les partenaires du marché", max_length=120, required=True
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "section_our_features",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        default="Une solution complète pour vos achats socialement responsables",
                                        max_length=120,
                                        required=True,
                                    ),
                                ),
                                (
                                    "constats",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "feature",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(max_length=60, required=True),
                                                        ),
                                                        (
                                                            "subtitle",
                                                            wagtail.blocks.RichTextBlock(
                                                                features=["bold", "italic"], required=True
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(required=True),
                                                        ),
                                                        ("url", wagtail.blocks.URLBlock(required=True)),
                                                    ]
                                                ),
                                            )
                                        ],
                                        min_num=1,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "section_why_call_siaes",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        default="Pourquoi faire appel à un prestataire inclusif ?",
                                        max_length=120,
                                        required=True,
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
    ]
