# Generated by Django 4.2.9 on 2024-01-24 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0008_alter_homepage_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaidArticleList",
            fields=[
                (
                    "articlelist_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cms.articlelist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.articlelist",),
        ),
    ]
