# Generated by Django 4.2.2 on 2024-03-21 15:39

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0009_paidarticlelist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="banner_cta_id",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="banner_cta_text",
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_cta_section",
            field=wagtail.fields.StreamField(
                [
                    (
                        "cta_primary",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "cta_id",
                                    wagtail.blocks.CharBlock(
                                        help_text="id du call to action (pour le suivi)", label="slug"
                                    ),
                                ),
                                ("cta_href", wagtail.blocks.CharBlock(label="Lien du call to action")),
                                ("cta_text", wagtail.blocks.CharBlock(label="Titre du call to action")),
                                (
                                    "cta_icon",
                                    wagtail.blocks.CharBlock(
                                        help_text=(
                                            'Bibliothèque <a href="https://remixicon.com/" '
                                            'target="_blanck">remixicon</a>'
                                        ),
                                        label="Icone du call to action",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="CTA primaire",
                        ),
                    ),
                    (
                        "cta_secondary",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "cta_id",
                                    wagtail.blocks.CharBlock(
                                        help_text="id du call to action (pour le suivi)", label="slug"
                                    ),
                                ),
                                ("cta_href", wagtail.blocks.CharBlock(label="Lien du call to action")),
                                ("cta_text", wagtail.blocks.CharBlock(label="Titre du call to action")),
                                (
                                    "cta_icon",
                                    wagtail.blocks.CharBlock(
                                        help_text=(
                                            'Bibliothèque <a href="https://remixicon.com/" '
                                            'target="_blanck">remixicon</a>'
                                        ),
                                        label="Icone du call to action",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="CTA secondaire",
                        ),
                    ),
                    (
                        "cta_primary_auth",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "cta_id",
                                    wagtail.blocks.CharBlock(
                                        help_text="id du call to action (pour le suivi)", label="slug"
                                    ),
                                ),
                                ("cta_href", wagtail.blocks.CharBlock(label="Lien du call to action")),
                                ("cta_text", wagtail.blocks.CharBlock(label="Titre du call to action")),
                                (
                                    "cta_icon",
                                    wagtail.blocks.CharBlock(
                                        help_text=(
                                            'Bibliothèque <a href="https://remixicon.com/" '
                                            'target="_blanck">remixicon</a>'
                                        ),
                                        label="Icone du call to action",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="CTA primaire connecté",
                        ),
                    ),
                    (
                        "cta_secondary_auth",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "cta_id",
                                    wagtail.blocks.CharBlock(
                                        help_text="id du call to action (pour le suivi)", label="slug"
                                    ),
                                ),
                                ("cta_href", wagtail.blocks.CharBlock(label="Lien du call to action")),
                                ("cta_text", wagtail.blocks.CharBlock(label="Titre du call to action")),
                                (
                                    "cta_icon",
                                    wagtail.blocks.CharBlock(
                                        help_text=(
                                            'Bibliothèque <a href="https://remixicon.com/" '
                                            'target="_blanck">remixicon</a>'
                                        ),
                                        label="Icone du call to action",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="CTA secondaire connecté",
                        ),
                    ),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
    ]
