# Generated by Django 4.2.10 on 2024-05-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0010_remove_homepage_banner_cta_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfoCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Titre de l'encart")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="A slug to identify this info card",
                        max_length=255,
                        verbose_name="slug",
                    ),
                ),
                ("content_card", models.TextField(verbose_name="Contenu")),
            ],
            options={
                "verbose_name": "Carte info",
                "verbose_name_plural": "Cartes infos",
            },
        ),
    ]
