# Generated by Django 4.2.13 on 2024-07-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0012_faqpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="intro",
            field=models.TextField(blank=True, null=True, verbose_name="Introduction de la page"),
        ),
        migrations.AlterField(
            model_name="faqpage",
            name="intro",
            field=models.TextField(blank=True, null=True, verbose_name="Introduction de la page"),
        ),
    ]
