# Generated by Django 5.1.6 on 2025-04-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0016_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advert",
            name="image",
        ),
        migrations.DeleteModel(
            name="InfoCard",
        ),
        migrations.DeleteModel(
            name="Advert",
        ),
    ]
