# Generated by Django 5.1.6 on 2025-04-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0016_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advert",
            name="image",
        ),
        migrations.RemoveField(
            model_name="articlepage",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="faqpage",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="articlepage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="articlepage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="faqpage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="faqpage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="InfoCard",
        ),
        migrations.RemoveField(
            model_name="paidarticlelist",
            name="articlelist_ptr",
        ),
        migrations.DeleteModel(
            name="Advert",
        ),
        migrations.DeleteModel(
            name="ArticleCategory",
        ),
        migrations.DeleteModel(
            name="ArticlePage",
        ),
        migrations.DeleteModel(
            name="FAQPage",
        ),
        migrations.DeleteModel(
            name="HomePage",
        ),
        migrations.DeleteModel(
            name="PaidArticleList",
        ),
    ]
