# Generated by Django 5.1.6 on 2025-04-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0017_remove_advert_image_delete_infocard_delete_advert"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paidarticlelist",
            name="articlelist_ptr",
        ),
        migrations.DeleteModel(
            name="ArticlePage",
        ),
        migrations.DeleteModel(
            name="PaidArticleList",
        ),
    ]
