# Generated by Django 5.1.6 on 2025-04-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0018_remove_paidarticlelist_articlelist_ptr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faqpage",
            name="categories",
        ),
        migrations.DeleteModel(
            name="ArticleCategory",
        ),
    ]
