# Generated by Django 5.1.6 on 2025-04-04 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0019_remove_faqpage_categories_delete_articlecategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="FAQPage",
        ),
        migrations.DeleteModel(
            name="HomePage",
        ),
    ]
