# Generated by Django 5.1.11 on 2025-10-09 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("website", models.URLField(blank=True, verbose_name="Site web")),
                ("logo_url", models.URLField(blank=True, max_length=500, verbose_name="Lien vers le logo")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date de modification")),
                ("data_description", models.TextField(blank=True, verbose_name="Description de la source de données")),
                (
                    "data_last_sync_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de dernière synchronisation"),
                ),
                ("logs", models.JSONField(default=list, editable=False, verbose_name="Logs historiques")),
            ],
            options={
                "verbose_name": "Label & certification",
                "verbose_name_plural": "Labels & certifications",
            },
        ),
    ]
