# Generated by Django 4.1.7 on 2023-06-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="data_description",
            field=models.TextField(blank=True, verbose_name="Description de la source de données"),
        ),
        migrations.AddField(
            model_name="label",
            name="data_last_sync_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de dernière synchronisation"),
        ),
        migrations.AddField(
            model_name="label",
            name="logs",
            field=models.JSONField(default=list, editable=False, verbose_name="Logs historiques"),
        ),
    ]
