# Generated by Django 5.1.11 on 2025-10-09 04:52

import django.utils.timezone
import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("labels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("siret", models.CharField(blank=True, max_length=14, verbose_name="Siret")),
                ("website", models.URLField(blank=True, verbose_name="Site web")),
                ("logo_url", models.URLField(blank=True, max_length=500, verbose_name="Lien vers le logo")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date de modification")),
                (
                    "email_domain_list",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        help_text="@entreprise.fr (sans le @)",
                        size=None,
                        verbose_name="Liste des noms de domaine d'e-mails",
                    ),
                ),
                (
                    "user_count",
                    models.IntegerField(
                        default=0,
                        help_text="Champ recalculé à intervalles réguliers",
                        verbose_name="Nombre d'utilisateurs",
                    ),
                ),
                (
                    "user_tender_count",
                    models.IntegerField(
                        default=0,
                        help_text="Champ recalculé à intervalles réguliers",
                        verbose_name="Nombre de besoins déposés par les utilisateurs",
                    ),
                ),
                (
                    "linkedin_buyer_count",
                    models.IntegerField(
                        default=0,
                        help_text="Champ renseigné par un ADMIN",
                        verbose_name="Nombre d'acheteurs sur LinkedIn",
                    ),
                ),
                (
                    "brevo_company_id",
                    models.CharField(blank=True, max_length=80, null=True, verbose_name="Brevo company id"),
                ),
                ("extra_data", models.JSONField(default=dict, editable=False, verbose_name="Données complémentaires")),
                ("logs", models.JSONField(default=list, editable=False, verbose_name="Logs historiques")),
                ("labels", models.ManyToManyField(blank=True, to="labels.label", verbose_name="Labels")),
            ],
            options={
                "verbose_name": "Entreprise",
                "verbose_name_plural": "Entreprises",
            },
        ),
    ]
