# Generated by Django 4.2.2 on 2023-07-04 15:38

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="email_domain_list",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="@entreprise.fr (sans le @)",
                size=None,
                verbose_name="Liste des noms de domaine d'e-mails",
            ),
        ),
    ]
