# Generated by Django 4.2.2 on 2023-11-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_company_email_domain_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="user_count",
            field=models.IntegerField(default=0, verbose_name="Nombre d'utilisateurs"),
        ),
    ]
