# Generated by Django 4.2.9 on 2024-03-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_company_user_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="user_tender_count",
            field=models.IntegerField(default=0, verbose_name="Nombre de besoins déposés par les utilisateurs"),
        ),
    ]
