# Generated by Django 4.2.9 on 2024-03-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_company_user_tender_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="linkedin_buyer_count",
            field=models.IntegerField(
                default=0, help_text="Champ renseigné par un ADMIN", verbose_name="Nombre d'acheteurs sur LinkedIn"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="user_count",
            field=models.IntegerField(
                default=0, help_text="Champ recalculé à intervalles réguliers", verbose_name="Nombre d'utilisateurs"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="user_tender_count",
            field=models.IntegerField(
                default=0,
                help_text="Champ recalculé à intervalles réguliers",
                verbose_name="Nombre de besoins déposés par les utilisateurs",
            ),
        ),
    ]
