# Generated by Django 4.2.17 on 2025-02-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0005_company_linkedin_buyer_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="brevo_company_id",
            field=models.CharField(
                blank=True, help_text="Identifiant de l'entreprise dans Brevo", null=True, verbose_name="ID Brevo"
            ),
        ),
    ]
