# Generated by Django 5.1.6 on 2025-06-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_company_linkedin_buyer_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="brevo_company_id",
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name="Brevo company id"),
        ),
        migrations.AddField(
            model_name="company",
            name="extra_data",
            field=models.JSONField(default=dict, editable=False, verbose_name="Données complémentaires"),
        ),
        migrations.AddField(
            model_name="company",
            name="logs",
            field=models.JSONField(default=list, editable=False, verbose_name="Logs historiques"),
        ),
    ]
