# Generated by Django 5.1.6 on 2025-07-29 15:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_add_brevo_fields"),
        ("siaes", "0090_alter_historicalsiae_contact_social_website_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySiaeClientReferenceMatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "similarity_score",
                    models.FloatField(
                        help_text="Score de similarité trigram entre les noms", verbose_name="Score de similarité"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="Nom de l'entreprise au moment de la correspondance",
                        max_length=255,
                        verbose_name="Nom de l'entreprise",
                    ),
                ),
                (
                    "client_reference_name",
                    models.CharField(
                        help_text="Nom de la référence client au moment de la correspondance",
                        max_length=255,
                        verbose_name="Nom de la référence client",
                    ),
                ),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[("pending", "En attente"), ("approved", "Approuvé"), ("rejected", "Rejeté")],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut de modération",
                    ),
                ),
                ("moderated_at", models.DateTimeField(blank=True, null=True, verbose_name="Date de modération")),
                ("moderation_notes", models.TextField(blank=True, verbose_name="Notes de modération")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date de modification")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="siae_client_reference_matches",
                        to="companies.company",
                        verbose_name="Entreprise",
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_matches_moderated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modéré par",
                    ),
                ),
                (
                    "siae_client_reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_matches",
                        to="siaes.siaeclientreference",
                        verbose_name="Référence client SIAE",
                    ),
                ),
            ],
            options={
                "verbose_name": "Correspondance entreprise-référence client",
                "verbose_name_plural": "Correspondances entreprise-référence client",
                "ordering": ["-similarity_score", "-created_at"],
                "unique_together": {("company", "siae_client_reference")},
            },
        ),
    ]
