# Generated by Django 5.1.6 on 2025-08-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_companysiaeclientreferencematch"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyLabel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                ("logo_url", models.URLField(max_length=500, verbose_name="Lien vers le logo")),
            ],
            options={
                "verbose_name": "Label",
                "verbose_name_plural": "Labels",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="labels",
            field=models.ManyToManyField(blank=True, to="companies.companylabel", verbose_name="Labels"),
        ),
    ]
