# Generated by Django 5.1.6 on 2025-08-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_companysiaeclientreferencematch"),
        ("labels", "0002_label_data_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="labels",
            field=models.ManyToManyField(blank=True, to="labels.label", verbose_name="Labels"),
        ),
    ]
