# Generated by Django 3.2.1 on 2021-06-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210607_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='Clé API'),
        ),
    ]
